"""Mine the AC19 census for the *families* of the 41 rows the 1,000-unit ball
cascade (`K3p_c12aut`) leaves unsolved.

A **family** is a set of census rows that share a relator up to the symmetry
group generated by cyclic rotation, relator inversion and the eight signed
permutations of ``{x, y}`` (``words.SIGNED_PERMS``).  ``orbit_key`` is the
canonical representative of that orbit, computed as
``min_phi canon_rel(phi(R))``; two relators are in the same orbit iff their
keys are equal.  Rotation and inversion are already quotiented by
``words.canon_rel``, so the key is a complete invariant of the orbit.

Everything here is read-only with respect to ``results/`` and ``data/``.

CLI
---
    PYTHONPATH=. python3 research/residual_20260909/theory/FAMILY_mine.py --build
        build (and cache) the census relator-orbit index

    PYTHONPATH=. python3 research/residual_20260909/theory/FAMILY_mine.py --report
        write FAMILY_mine.json: per-family tables used by FAMILY_DATA.md
"""
import argparse
import csv
import glob
import json
import os
import pickle
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

from experiments.equivalence_classes.lib.words import (
    SIGNED_PERMS, abelian_det, apply_hom, apply_pair, canon_pair, canon_rel,
    cyc_reduce, exp_sums, inv, replay_move, rot,
)

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
CENSUS = ROOT / 'data' / 'AC19_extended_aut_min.csv'
BALL = ROOT / 'results' / 'heuristic_search' / 'ac19_ball_cascade_full_1k'
PUB = ROOT / 'results' / 'heuristic_search' / 'ac19_final_policy_full_1k'
UNSOLVED = BALL / 'unsolved.csv'
CACHE = HERE / 'FAMILY_index.pkl'

LOST_ROWS = ('ac19_17417', 'ac19_31624', 'ac19_51124',
             'ac19_56260', 'ac19_57787', 'ac19_65876')

# --------------------------------------------------------------------------
# orbit keys
# --------------------------------------------------------------------------
_OK_CACHE = {}


def orbit_key(word):
    """Canonical representative of ``word`` under rotation / inversion / the
    eight signed permutations of the basis."""
    value = _OK_CACHE.get(word)
    if value is None:
        value = min(canon_rel(apply_hom(word, img)) for _, img in SIGNED_PERMS)
        _OK_CACHE[word] = value
    return value


def normalizers(word, key=None):
    """Every signed permutation ``phi`` with ``canon_rel(phi(word)) == key``
    (default ``key = orbit_key(word)``), as ``(label, img)`` pairs."""
    key = orbit_key(word) if key is None else key
    return [(label, img) for label, img in SIGNED_PERMS
            if canon_rel(apply_hom(word, img)) == key]


def normalize_row(r1, r2, key):
    """Put a census row into the family frame of ``key``.

    Returns ``(role, label, img, companion)`` where ``role`` is 1 or 2
    according to which relator carries the family orbit, and ``companion`` is
    the canonical form of the *other* relator after applying ``img``.  The
    signed permutation is chosen to make the companion lexicographically
    smallest, so the frame is a function of the row and the family alone.
    """
    best = None
    for role, (own, other) in ((1, (r1, r2)), (2, (r2, r1))):
        if orbit_key(own) != key:
            continue
        for label, img in normalizers(own, key):
            companion = canon_rel(apply_hom(other, img))
            cand = (companion, role, label)
            if best is None or cand < best[0:3]:
                best = (companion, role, label, img)
    if best is None:
        return None
    companion, role, label, img = best
    return dict(role=role, perm=label, images=img, companion=companion)


# --------------------------------------------------------------------------
# census + certificate access
# --------------------------------------------------------------------------
def load_census():
    with open(CENSUS, newline='') as stream:
        return list(csv.DictReader(stream))


def load_unsolved():
    with open(UNSOLVED, newline='') as stream:
        return list(csv.DictReader(stream))


def build_index(rows=None, verbose=True):
    """``orbit_key -> [(name, role), ...]`` over the whole census."""
    rows = load_census() if rows is None else rows
    index = defaultdict(list)
    for row in rows:
        k1, k2 = orbit_key(row['r1']), orbit_key(row['r2'])
        index[k1].append((row['name'], 1))
        if k2 != k1:
            index[k2].append((row['name'], 2))
    index = dict(index)
    if verbose:
        print(f'index: {len(index)} orbit keys over {len(rows)} rows', file=sys.stderr)
    return index


def load_index(rebuild=False):
    if CACHE.exists() and not rebuild:
        with open(CACHE, 'rb') as stream:
            return pickle.load(stream)
    index = build_index()
    with open(CACHE, 'wb') as stream:
        pickle.dump(index, stream)
    return index


def _shards(directory):
    out = []
    for path in sorted(glob.glob(str(Path(directory) / 'rows_*.jsonl'))):
        match = re.match(r'rows_(\d+)_(\d+)\.jsonl', os.path.basename(path))
        out.append((int(match.group(1)), int(match.group(2)), path))
    return out


def load_records(names, directory=BALL):
    """Certificate records for ``names`` from a census result directory."""
    want = set(names)
    out = {}
    for _lo, _hi, path in _shards(directory):
        with open(path) as stream:
            for line in stream:
                if not line.strip():
                    continue
                record = json.loads(line)
                if record.get('name') in want:
                    out[record['name']] = record
        if len(out) == len(want):
            break
    return out


# --------------------------------------------------------------------------
# path analysis
# --------------------------------------------------------------------------
def parse_move(text):
    target, jsign, k1, k2 = (int(v) for v in text.split('_'))
    return target, jsign, k1, k2


def step_summary(states, steps):
    """One compact token per certificate step: ``S1``/``S2`` for a
    substitution onto relator 1/2, ``A`` for an ambient Nielsen map."""
    out = []
    for step in steps:
        if step.get('kind') == 'automorphism':
            out.append('A')
        else:
            target = parse_move(step['move'])[0]
            out.append(f'S{target}')
    return out


def donor_trace(record, family_relator_canon):
    """For each substitution step, which relator was the *donor* (source), and
    was the root family relator still intact at that point?

    Returns a dict with the first-donor role, the number of steps until the
    family relator is first modified, and the compact step string.
    """
    states = [tuple(s) for s in record['states']]
    steps = record['steps']
    tokens = step_summary(states, steps)
    fam = family_relator_canon
    first_touch = None       # index of the first step that removes fam from the pair
    first_donor = None       # 'family' or 'companion'
    for i, (state, step) in enumerate(zip(states, steps)):
        present = fam in (canon_rel(state[0]), canon_rel(state[1]))
        if step.get('kind') == 'automorphism':
            if present and first_touch is None:
                first_touch = i
                first_donor = 'automorphism'
            continue
        target = parse_move(step['move'])[0]
        # the donor is the *other* relator
        donor_word = canon_rel(state[1] if target == 1 else state[0])
        target_word = canon_rel(state[0] if target == 1 else state[1])
        if first_donor is None and present:
            if donor_word == fam:
                first_donor = 'family'
            elif target_word == fam:
                first_donor = 'companion'   # family relator is being overwritten
        if present and target_word == fam and first_touch is None:
            first_touch = i
    return dict(tokens=tokens, first_donor=first_donor, first_touch=first_touch,
                n_steps=len(steps))


def replay_check(pair, states, steps):
    """Independently re-run a mixed certificate with words.replay_move /
    words.apply_pair; returns True iff every stored state is reproduced."""
    cur = canon_pair(*pair)
    if list(cur) != [canon_rel(states[0][0]), canon_rel(states[0][1])] and \
       tuple(cur) != tuple(states[0]):
        cur = tuple(states[0])
    for i, step in enumerate(steps):
        if step.get('kind') == 'automorphism':
            cur = apply_pair(cur, step['images'])
        else:
            cur = replay_move(cur, parse_move(step['move']))
        if tuple(cur) != tuple(states[i + 1]):
            return False
    return True


# --------------------------------------------------------------------------
# family assembly
# --------------------------------------------------------------------------
def family(key, index=None, census=None, records=True):
    index = load_index() if index is None else index
    census = load_census() if census is None else census
    by_name = {row['name']: row for row in census}
    members = []
    for name, _role in index.get(key, ()):
        row = by_name[name]
        frame = normalize_row(row['r1'], row['r2'], key)
        members.append(dict(name=name, index=int(row['name'].split('_')[1]),
                            r1=row['r1'], r2=row['r2'], **frame))
    members.sort(key=lambda m: m['index'])
    if records:
        recs = load_records([m['name'] for m in members])
        for m in members:
            r = recs.get(m['name'])
            m['record'] = r
    return members


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--build', action='store_true', help='rebuild the orbit index cache')
    parser.add_argument('--families', action='store_true', help='print the family table')
    args = parser.parse_args(argv)
    index = load_index(rebuild=args.build)
    if args.families:
        uns = load_unsolved()
        fams = defaultdict(list)
        for row in uns:
            fams[orbit_key(row['r1'])].append(row['name'])
        print(f"{'family':22s} {'|R|':>3} {'ex':>3} {'ey':>3} {'unsolved':>8} {'census':>7}")
        for key, names in sorted(fams.items(), key=lambda kv: (-len(kv[1]), kv[0])):
            ex, ey = exp_sums(key)
            print(f'{key:22s} {len(key):3d} {ex:3d} {ey:3d} {len(names):8d} '
                  f'{len(index.get(key, [])):7d}  ' + ','.join(names))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
