"""Mine the AC19 census for the *families* of the 41 rows the 1,000-unit ball
cascade (`K3p_c12aut`) leaves unsolved.

A **family** is a set of census rows that share a relator up to the symmetry
group generated by cyclic rotation, relator inversion and the eight signed
permutations of ``{x, y}`` (``words.SIGNED_PERMS``).  ``orbit_key`` is the
canonical representative of that orbit, computed as
``min_phi canon_rel(phi(R))``; two relators are in the same orbit iff their
keys are equal.  Rotation and inversion are already quotiented by
``words.canon_rel``, so the key is a complete invariant of the orbit.

Everything here is read-only with respect to ``results/`` and ``data/``.

CLI
---
    PYTHONPATH=. python3 research/residual_20260909/theory/FAMILY_mine.py --build
        build (and cache) the census relator-orbit index

    PYTHONPATH=. python3 research/residual_20260909/theory/FAMILY_mine.py --families
        print the 19 residual families

    PYTHONPATH=. python3 research/residual_20260909/theory/FAMILY_mine.py --report
        write FAMILY_mine.json: per-family tables used by FAMILY_DATA.md

Beyond the CLI this module is the library the proofs use:
``w_children`` / ``w_ball`` / ``w_path`` enumerate R-preserving (companion-only)
Definition 2.1 moves, ``magnus_frame`` / ``magnus_word`` compute and check the
Magnus/HNN frame of a family relator, and ``build_corpus`` / ``LayeredTable``
turn the published census certificates into an extra terminal table for the
ball-aware searches.  See FAMILY_THEORY.md.
"""
import argparse
import csv
import glob
import json
import os
import pickle
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

from experiments.equivalence_classes.lib.words import (
    SIGNED_PERMS, apply_hom, canon_pair, canon_rel, cyc_reduce, exp_sums, inv,
    replay_move,
)

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
CENSUS = ROOT / 'data' / 'AC19_extended_aut_min.csv'
BALL = ROOT / 'results' / 'heuristic_search' / 'ac19_ball_cascade_full_1k'
PUB = ROOT / 'results' / 'heuristic_search' / 'ac19_final_policy_full_1k'
UNSOLVED = BALL / 'unsolved.csv'
CACHE = HERE / 'FAMILY_index.pkl'

# The six rows the published frozen census solved (in its plain-S20 stage) and
# the ball cascade lost; all six are inside the 41.
LOST_ROWS = ('ac19_17417', 'ac19_31624', 'ac19_51124',
             'ac19_56260', 'ac19_57787', 'ac19_65876')

# --------------------------------------------------------------------------
# orbit keys
# --------------------------------------------------------------------------
_OK_CACHE = {}


def orbit_key(word):
    """Canonical representative of ``word`` under rotation / inversion / the
    eight signed permutations of the basis."""
    value = _OK_CACHE.get(word)
    if value is None:
        value = min(canon_rel(apply_hom(word, img)) for _, img in SIGNED_PERMS)
        _OK_CACHE[word] = value
    return value


def normalizers(word, key=None):
    """Every signed permutation ``phi`` with ``canon_rel(phi(word)) == key``
    (default ``key = orbit_key(word)``), as ``(label, img)`` pairs."""
    key = orbit_key(word) if key is None else key
    return [(label, img) for label, img in SIGNED_PERMS
            if canon_rel(apply_hom(word, img)) == key]


def normalize_row(r1, r2, key):
    """Put a census row into the family frame of ``key``.

    Returns ``(role, label, img, companion)`` where ``role`` is 1 or 2
    according to which relator carries the family orbit, and ``companion`` is
    the canonical form of the *other* relator after applying ``img``.  The
    signed permutation is chosen to make the companion lexicographically
    smallest, so the frame is a function of the row and the family alone.
    """
    best = None
    for role, (own, other) in ((1, (r1, r2)), (2, (r2, r1))):
        if orbit_key(own) != key:
            continue
        for label, img in normalizers(own, key):
            companion = canon_rel(apply_hom(other, img))
            cand = (companion, role, label)
            if best is None or cand < best[0:3]:
                best = (companion, role, label, img)
    if best is None:
        return None
    companion, role, label, img = best
    return dict(role=role, perm=label, images=img, companion=companion)


# --------------------------------------------------------------------------
# census + certificate access
# --------------------------------------------------------------------------
def load_census():
    with open(CENSUS, newline='') as stream:
        return list(csv.DictReader(stream))


def load_unsolved():
    with open(UNSOLVED, newline='') as stream:
        return list(csv.DictReader(stream))


def build_index(rows=None, verbose=True):
    """``orbit_key -> [(name, role), ...]`` over the whole census."""
    rows = load_census() if rows is None else rows
    index = defaultdict(list)
    for row in rows:
        k1, k2 = orbit_key(row['r1']), orbit_key(row['r2'])
        index[k1].append((row['name'], 1))
        if k2 != k1:
            index[k2].append((row['name'], 2))
    index = dict(index)
    if verbose:
        print(f'index: {len(index)} orbit keys over {len(rows)} rows', file=sys.stderr)
    return index


def load_index(rebuild=False):
    if CACHE.exists() and not rebuild:
        with open(CACHE, 'rb') as stream:
            return pickle.load(stream)
    index = build_index()
    with open(CACHE, 'wb') as stream:
        pickle.dump(index, stream)
    return index


def _shards(directory):
    out = []
    for path in sorted(glob.glob(str(Path(directory) / 'rows_*.jsonl'))):
        match = re.match(r'rows_(\d+)_(\d+)\.jsonl', os.path.basename(path))
        out.append((int(match.group(1)), int(match.group(2)), path))
    return out


def load_records(names, directory=BALL):
    """Certificate records for ``names`` from a census result directory."""
    want = set(names)
    out = {}
    for _lo, _hi, path in _shards(directory):
        with open(path) as stream:
            for line in stream:
                if not line.strip():
                    continue
                record = json.loads(line)
                if record.get('name') in want:
                    out[record['name']] = record
        if len(out) == len(want):
            break
    return out


# --------------------------------------------------------------------------
# path analysis
# --------------------------------------------------------------------------
def parse_move(text):
    target, jsign, k1, k2 = (int(v) for v in text.split('_'))
    return target, jsign, k1, k2


def step_summary(states, steps):
    """One compact token per certificate step: ``S1``/``S2`` for a
    substitution onto relator 1/2, ``A`` for an ambient Nielsen map."""
    out = []
    for step in steps:
        if step.get('kind') == 'automorphism':
            out.append('A')
        else:
            target = parse_move(step['move'])[0]
            out.append(f'S{target}')
    return out


def donor_trace(record, family_relator_canon):
    """For each substitution step, which relator was the *donor* (source), and
    was the root family relator still intact at that point?

    Returns a dict with the first-donor role, the number of steps until the
    family relator is first modified, and the compact step string.
    """
    states = [tuple(s) for s in record['states']]
    steps = record['steps']
    tokens = step_summary(states, steps)
    fam = family_relator_canon
    first_touch = None       # index of the first step that removes fam from the pair
    first_donor = None       # 'family' or 'companion'
    for i, (state, step) in enumerate(zip(states, steps)):
        present = fam in (canon_rel(state[0]), canon_rel(state[1]))
        if step.get('kind') == 'automorphism':
            if present and first_touch is None:
                first_touch = i
                first_donor = 'automorphism'
            continue
        target = parse_move(step['move'])[0]
        # the donor is the *other* relator
        donor_word = canon_rel(state[1] if target == 1 else state[0])
        target_word = canon_rel(state[0] if target == 1 else state[1])
        if first_donor is None and present:
            if donor_word == fam:
                first_donor = 'family'
            elif target_word == fam:
                first_donor = 'companion'   # family relator is being overwritten
        if present and target_word == fam and first_touch is None:
            first_touch = i
    return dict(tokens=tokens, first_donor=first_donor, first_touch=first_touch,
                n_steps=len(steps))


# --------------------------------------------------------------------------
# family assembly
# --------------------------------------------------------------------------
def family(key, index=None, census=None, records=True):
    """Every census row carrying the orbit ``key``, in the family frame, with
    its census certificate record attached when ``records``."""
    index = load_index() if index is None else index
    census = load_census() if census is None else census
    by_name = {row['name']: row for row in census}
    members = []
    for name, _role in index.get(key, ()):
        row = by_name[name]
        frame = normalize_row(row['r1'], row['r2'], key)
        members.append(dict(name=name, index=int(row['name'].split('_')[1]),
                            r1=row['r1'], r2=row['r2'], **frame))
    members.sort(key=lambda member: member['index'])
    if records:
        found = load_records([member['name'] for member in members])
        for member in members:
            member['record'] = found.get(member['name'])
    return members


# --------------------------------------------------------------------------
# the backward ball (whichever representation is currently shipped)
# --------------------------------------------------------------------------
TABLES = ROOT / 'research' / 'residual_20260909' / 'tables'
_BALL = {}

# sha256 of tables/ball_cap12_aut.pkl as verified against its manifest at the
# start of this session.  A concurrent session is migrating that manifest to a
# compact .npz, so the loader tries whichever representation is loadable and,
# if the manifest is missing entirely, checks the digest against this pin.
BALL_CAP12_AUT_SHA256 = 'c12115452e9d4d99c2d6d057ff8324ce06516f4043d9a15026f59916f6f46cfb'
BALL_CAP12_AUT_SIZE = 1488649


def load_ball(stem='ball_cap12_aut'):
    """Load ``tables/<stem>``, accepting the ``.npz`` compact table or the
    ``.pkl`` dict, and verifying the digest here when no manifest is present."""
    import hashlib
    from research.residual_20260909 import backward_table as _bt
    if stem in _BALL:
        return _BALL[stem]
    errors = []
    for suffix in ('.npz', '.pkl'):
        path = TABLES / f'{stem}{suffix}'
        if not path.exists():
            continue
        try:
            _BALL[stem] = _bt.load(path)
            return _BALL[stem]
        except Exception as exc:                      # missing / renamed manifest
            errors.append(f'{path.name}: {exc}')
    path = TABLES / f'{stem}.pkl'
    if stem == 'ball_cap12_aut' and path.exists():
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        if digest != BALL_CAP12_AUT_SHA256:
            raise ValueError(f'{path}: sha256 {digest} != pinned {BALL_CAP12_AUT_SHA256}')
        table = _bt.load(path, verify_sha256=False)
        if len(table) != BALL_CAP12_AUT_SIZE:
            raise ValueError(f'{path}: {len(table)} states, expected {BALL_CAP12_AUT_SIZE}')
        _BALL[stem] = table
        return table
    raise FileNotFoundError(f'no loadable table for {stem} in {TABLES}: ' + '; '.join(errors))


# --------------------------------------------------------------------------
# R-preserving ("W-") moves
# --------------------------------------------------------------------------
def w_children(pair, cap):
    """``{child_pair: move}`` for every Definition 2.1 move of ``pair`` that
    leaves one relator intact (an *R-preserving* move: only the companion is
    rewritten) and keeps both relators at length ``<= cap``.

    Children are produced with ``words.replay_move`` itself, so every move in
    the returned dict is literally replayable.
    """
    out = {}
    for target in (1, 2):
        keep = canon_rel(pair[2 - target])
        for jsign in (1, -1):
            for k1 in range(len(pair[target - 1])):
                for k2 in range(len(pair[2 - target])):
                    move = (target, jsign, k1, k2)
                    child = replay_move(pair, move)
                    if keep not in child or max(map(len, child)) > cap:
                        continue
                    out.setdefault(child, move)
    return out


def w_ball(pair, cap, depth):
    """BFS over R-preserving moves; returns ``{pair: (parent, move)}``."""
    root = canon_pair(*pair)
    parent = {root: (None, None)}
    frontier = [root]
    for _ in range(depth):
        nxt = []
        for state in frontier:
            for child, move in w_children(state, cap).items():
                if child in parent:
                    continue
                parent[child] = (state, move)
                nxt.append(child)
        frontier = nxt
        if not nxt:
            break
    return parent


def w_path(parent, state):
    """``(states, moves)`` from the BFS root of ``parent`` down to ``state``."""
    states, moves = [state], []
    while parent[state][0] is not None:
        previous, move = parent[state]
        states.append(previous)
        moves.append(move)
        state = previous
    return states[::-1], moves[::-1]


# --------------------------------------------------------------------------
# the certificate corpus ("trail table")
# --------------------------------------------------------------------------
def certificate_entries(record):
    """``[(key, depth, successor_key, move), ...]`` for one verified census
    certificate, in exactly the schema ``backward_table.tail`` walks.

    Returns ``None`` unless the record is a verified solve whose stored mixed
    path ends at the canonical trivial pair with no packed elementary tail (a
    packed tail is not walkable as a successor chain).
    """
    from experiments.search.heuristic_1k import pack
    if not record.get('solved') or not record.get('verified'):
        return None
    if record.get('elementary_tail'):
        return None
    states = [tuple(state) for state in record['states']]
    if states[-1] != ('Y', 'X'):
        return None
    entries = []
    depth = len(states) - 1
    for i, step in enumerate(record['steps']):
        move = (step['images'] if step.get('kind') == 'automorphism'
                else tuple(int(v) for v in step['move'].split('_')))
        entries.append((pack(states[i]), depth - i, pack(states[i + 1]), move))
    return entries


def build_corpus(records, base=None, provenance=None):
    """``{key: (depth, successor_key, move)}`` over many certificates.

    ``base`` (a backward ball) is subtracted: a state the ball already closes
    contributes nothing.  ``provenance``, if a dict, collects
    ``key -> record name`` for the shallowest contributor.
    """
    corpus = {}
    for record in records:
        entries = certificate_entries(record)
        if entries is None:
            continue
        for key, depth, successor, move in entries:
            if base is not None and key in base:
                continue
            current = corpus.get(key)
            if current is None or current[0] > depth:
                corpus[key] = (depth, successor, move)
                if provenance is not None:
                    provenance[key] = record.get('name')
    return corpus


def iter_records(directory=BALL):
    """Stream every certificate record of a census result directory."""
    for _lo, _hi, path in _shards(directory):
        with open(path) as stream:
            for line in stream:
                if line.strip():
                    yield json.loads(line)


class LayeredTable:
    """A corpus dict layered over a backward ball, with the ball's read API.

    ``final_policy_ball`` / ``mid_search_ball`` / ``plain_search_ball`` only ask
    a table for ``key in table``, ``table.get(key)``, ``table[key]`` and
    ``len(table)``, and read a tail with ``backward_table.tail``, which walks
    ``table[key] -> (depth, successor, move)``.  This object answers all of
    those from the corpus first and the ball second, so it is a drop-in
    replacement for the ball.
    """
    __slots__ = ('extra', 'base')

    def __init__(self, extra, base):
        self.extra, self.base = extra, base

    def __len__(self):
        return len(self.extra) + len(self.base)

    def __contains__(self, key):
        return key in self.extra or key in self.base

    def get(self, key, default=None):
        value = self.extra.get(key)
        return value if value is not None else self.base.get(key, default)

    def __getitem__(self, key):
        value = self.extra.get(key)
        if value is not None:
            return value
        return self.base[key]


# --------------------------------------------------------------------------
# Magnus frame of a one-relator family group G = <x, y | R>
# --------------------------------------------------------------------------
def magnus_frame(word):
    """The Magnus/HNN data of ``G = <x, y | word>``, when one exponent sum
    divides the other so a single Nielsen shear puts one of them at zero.

    Returns a dict with

    ``images``   the ambient shear (``x -> x y^m`` or ``y -> y x^k``) applied
                 to reach the frame -- an ordinary transport step, not an AC
                 move;
    ``relator``  the transported relator ``R~`` (exponent sum 0 in ``stable``);
    ``stable``   the stable letter of the HNN decomposition (the generator
                 whose exponent sum in ``R~`` is 0);
    ``base``     the other generator;  ``mu``/``nu`` the index range of the
                 conjugates ``b_i = t^i b t^-i`` occurring in the rewritten
                 relator, and ``star`` that relator as ``[(i, sign), ...]``.

    ``None`` when neither exponent sum divides the other (no single-shear
    frame; a frame still exists but needs a longer change of basis).
    """
    # The stable letter of the Magnus/HNN decomposition is the generator whose
    # exponent sum in the relator is ZERO: it is the one that survives in the
    # retraction G -> Z killing the relator, and the base is generated by the
    # conjugates of the other generator.  (Check against BS(m, m+1) =
    # b^-1 a^m b a^-(m+1): exp_b = 0 and b is the stable letter, as in
    # STALLED_BS_THEORY.md section 1.)
    ex, ey = exp_sums(word)
    if ex == 0:
        images, transported, stable, base = {'x': 'x', 'y': 'y'}, cyc_reduce(word), 'x', 'y'
    elif ey == 0:
        images, transported, stable, base = {'x': 'x', 'y': 'y'}, cyc_reduce(word), 'y', 'x'
    elif ex % ey == 0:                      # y -> y x^(-ex/ey) puts exp_x at 0
        k = ex // ey
        images = {'x': 'x', 'y': 'y' + ('x' * (-k) if k < 0 else 'X' * k)}
        transported, stable, base = cyc_reduce(apply_hom(word, images)), 'x', 'y'
    elif ey % ex == 0:                      # x -> x y^(-ey/ex) puts exp_y at 0
        m = ey // ex
        images = {'x': 'x' + ('y' * (-m) if m < 0 else 'Y' * m), 'y': 'y'}
        transported, stable, base = cyc_reduce(apply_hom(word, images)), 'y', 'x'
    else:
        return None
    assert exp_sums(transported)['xy'.index(stable)] == 0
    level, star = 0, []
    for char in transported:
        if char == stable:
            level += 1
        elif char == stable.upper():
            level -= 1
        elif char == base:
            star.append((level, 1))
        else:
            star.append((level, -1))
    indices = [i for i, _ in star]
    counts = Counter(indices)
    mu, nu = min(indices), max(indices)
    return dict(images=images, relator=transported, stable=stable, base=base,
                mu=mu, nu=nu, star=star, counts={i: counts[i] for i in range(mu, nu + 1)},
                extremes_once=(counts[mu] == 1, counts[nu] == 1))


def magnus_word(frame):
    """Re-expand a Magnus rewriting into a word in ``x, y`` -- the check that
    ``star`` really is the transported relator."""
    stable, base = frame['stable'], frame['base']
    out = []
    for level, sign in frame['star']:
        conj = (stable if level > 0 else stable.upper()) * abs(level)
        out.append(conj + (base if sign > 0 else base.upper()) + inv(conj))
    return cyc_reduce(''.join(out))


def family_report(index=None, census=None):
    """The per-family table FAMILY_DATA.md is built from."""
    index = load_index() if index is None else index
    census = load_census() if census is None else census
    unsolved = load_unsolved()
    by_family = defaultdict(list)
    for row in unsolved:
        by_family[orbit_key(row['r1'])].append(row['name'])
    unsolved_names = {row['name'] for row in unsolved}
    out = []
    for key, names in sorted(by_family.items(), key=lambda kv: (-len(kv[1]), kv[0])):
        members = family(key, index=index, census=census, records=True)
        routes = Counter()
        first_move = Counter()
        survives = []
        lengths = dict(solved=[], unsolved=[])
        for member in members:
            record = member['record']
            solved = bool((record or {}).get('solved'))
            lengths['solved' if solved else 'unsolved'].append(len(member['companion']))
            if not solved:
                continue
            routes[record['policy_route']] += 1
            own = canon_rel(member['r1'] if member['role'] == 1 else member['r2'])
            states = [tuple(state) for state in record['states']]
            steps = record['steps']
            if steps:
                step = steps[0]
                if step.get('kind') == 'automorphism':
                    first_move['automorphism'] += 1
                else:
                    target = parse_move(step['move'])[0]
                    first_move['rewrites_R' if canon_rel(states[0][target - 1]) == own
                               else 'keeps_R'] += 1
            gone = next((i for i, state in enumerate(states)
                         if own not in (canon_rel(state[0]), canon_rel(state[1]))), len(states))
            survives.append(gone)
        exps = exp_sums(key)
        out.append(dict(
            family=key, length=len(key), exp_x=exps[0], exp_y=exps[1],
            census_rows=len(members), unsolved=sorted(names),
            n_unsolved=len(names),
            routes=dict(routes), first_move=dict(first_move),
            steps_until_R_gone=dict(
                minimum=min(survives) if survives else None,
                median=sorted(survives)[len(survives) // 2] if survives else None,
                maximum=max(survives) if survives else None),
            companion_length=dict(
                solved=sorted(lengths['solved']), unsolved=sorted(lengths['unsolved'])),
        ))
    return out


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--build', action='store_true', help='rebuild the orbit index cache')
    parser.add_argument('--families', action='store_true', help='print the family table')
    parser.add_argument('--report', action='store_true',
                        help='write FAMILY_mine.json (the per-family tables)')
    args = parser.parse_args(argv)
    index = load_index(rebuild=args.build)
    if args.families:
        uns = load_unsolved()
        fams = defaultdict(list)
        for row in uns:
            fams[orbit_key(row['r1'])].append(row['name'])
        print(f"{'family':22s} {'|R|':>3} {'ex':>3} {'ey':>3} {'unsolved':>8} {'census':>7}")
        for key, names in sorted(fams.items(), key=lambda kv: (-len(kv[1]), kv[0])):
            ex, ey = exp_sums(key)
            print(f'{key:22s} {len(key):3d} {ex:3d} {ey:3d} {len(names):8d} '
                  f'{len(index.get(key, [])):7d}  ' + ','.join(names))
    if args.report:
        report = family_report(index=index)
        path = HERE / 'FAMILY_mine.json'
        with open(path, 'w') as stream:
            json.dump(report, stream, indent=1)
        print(f'wrote {path} ({len(report)} families)')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
