"""Mine the AC19 census certificates for FOUR-BLOCK roots.

A *four-block* cyclic relator is a cyclically reduced word with exactly four
maximal generator runs, i.e. ``y^a x^b y^c x^d`` with ``a,b,c,d != 0`` (two
y-blocks and two x-blocks).  The residual audit
(``research/residual_20260909/THEOREMS_PROOFS_AND_FREQUENCY.md`` section 6)
identifies this as the largest structural family left unsolved: 293 of the 727
residual roots carry such a relator.

This script answers Task A of the four-block brief against the *solved* part of
the frozen census
``results/heuristic_search/ac19_final_policy_full_1k/rows_*.jsonl`` (read-only):

  * how many solved roots carry a four-block relator, by route;
  * the distribution of the exponent patterns (a,b,c,d) modulo the symmetry
    group generated by block rotation, inversion, x<->y relabelling and the two
    sign flips (32 elements, see ``ORBIT_GENERATORS``);
  * how the certified path treats the four-block relator: donor or target,
    steps until it changes, what an ambient Nielsen map does to it;
  * the shortest prefix of the path that reaches a state one of the three
    proved gates closes (two-block unimodular / one-occurrence primitive /
    consecutive-BS with an accepting preflight), and the most frequent 2-4
    step macro patterns that bridge a four-block root to such a gate.

Nothing under ``research/supermoves_20260908/``, ``results/`` or ``data/`` is
written.  No search is run: only the saved states/steps are replayed with
``words.replay_move`` and O(length) recognizers are evaluated.

Usage:
    PYTHONPATH=. python3 research/residual_20260909/theory/FOURBLOCK_mine.py
    PYTHONPATH=. python3 research/residual_20260909/theory/FOURBLOCK_mine.py 5   # 5 shards only
"""
from __future__ import annotations

import glob
import json
import os
import sys
from collections import Counter, defaultdict

from experiments.equivalence_classes.lib.words import (
    abelian_det, apply_pair, canon_pair, canon_rel, exp_sums, replay_move,
)
from experiments.search.heuristic_1k import NIELSEN
from research.supermoves_20260908.bs_preflight import preflight
from research.supermoves_20260908.cheap_gates import (
    bs_gate, canonical_two_block_gate, one_occurrence_donor, two_block_gate,
)

ROWS_GLOB = "results/heuristic_search/ac19_final_policy_full_1k/rows_*.jsonl"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT_JSON = os.path.join(HERE, "FOURBLOCK_mine.json")
OUT_EXAMPLES = os.path.join(HERE, "FOURBLOCK_examples.jsonl")

GATE_SCAN_DEPTH = 8          # how many leading states of each path we gate-test
MAX_EXAMPLES_PER_PATTERN = 3


# --------------------------------------------------------------------------
# block structure
# --------------------------------------------------------------------------

def blocks(word):
    """Maximal cyclic runs of ``word`` as [(generator, signed exponent), ...].

    ``word`` must be cyclically reduced (canon_rel output is).  For a word using
    both generators the result starts at a block boundary, so the list is the
    cyclic block sequence read from an arbitrary but deterministic origin.
    """
    if not word:
        return []
    lowers = {c.lower() for c in word}
    if len(lowers) == 1:
        sign = 1 if word[0].islower() else -1
        return [(word[0].lower(), sign * len(word))]
    start = next(i for i in range(len(word)) if word[i].lower() != word[i - 1].lower())
    rotated = word[start:] + word[:start]
    out = []
    gen, count = rotated[0].lower(), 0
    for c in rotated:
        g, s = c.lower(), (1 if c.islower() else -1)
        if g == gen:
            count += s
        else:
            out.append((gen, count))
            gen, count = g, s
    out.append((gen, count))
    return out


def four_block_tuple(word):
    """(a,b,c,d) with the word read as y^a x^b y^c x^d, or None.

    The returned tuple starts at a y-block; it is one of the two rotations of
    the block cycle that do so, chosen deterministically (the first in
    ``blocks`` order).
    """
    bl = blocks(word)
    if len(bl) != 4:
        return None
    if bl[0][0] == "x":
        bl = bl[1:] + bl[:1]
    return (bl[0][1], bl[1][1], bl[2][1], bl[3][1])


def n_blocks(word):
    return len(blocks(word))


# --------------------------------------------------------------------------
# the symmetry group on exponent 4-tuples
# --------------------------------------------------------------------------

def _tau(t):                      # x <-> y relabelling, then rotate to a y-block
    a, b, c, d = t
    return (b, c, d, a)


def _iota(t):                     # relator inversion
    a, b, c, d = t
    return (-c, -b, -a, -d)


def _flip_x(t):                   # x -> X
    a, b, c, d = t
    return (a, -b, c, -d)


def _flip_y(t):                   # y -> Y
    a, b, c, d = t
    return (-a, b, -c, d)


ORBIT_GENERATORS = (_tau, _iota, _flip_x, _flip_y)


def orbit(t):
    seen = {tuple(t)}
    frontier = [tuple(t)]
    while frontier:
        cur = frontier.pop()
        for g in ORBIT_GENERATORS:
            nxt = g(cur)
            if nxt not in seen:
                seen.add(nxt)
                frontier.append(nxt)
    return seen


def canon_tuple(t):
    """Lexicographically least member of the symmetry orbit of ``t``."""
    return min(orbit(t))


def family_of(t):
    """Symmetry-invariant family label of a four-block exponent tuple.

    ``ey = a+c`` and ``ex = b+d`` are the relator's exponent sums; the unordered
    pair {|ey|,|ex|} is invariant under the whole symmetry group, and |det| = 1
    forces gcd(|ey|,|ex|) = 1.

      bs_stable_s<k>  one exponent sum vanishes: the relator is
                      t u^p t^-1 u^q with t = <generator>^k a *stable power*
                      (k = 1 is exactly the consecutive-BS donor shape of T5,
                      whose consecutivity |p+q| = 1 is then forced by det = 1)
      merge_pm1       the two blocks of one generator are both +-1 and have the
                      SAME sign: a single Nielsen map merges them (see theory)
      generic         everything else
    """
    a, b, c, d = t
    ey, ex = a + c, b + d
    if ey == 0:
        return "bs_stable_s%d" % abs(a)
    if ex == 0:
        return "bs_stable_s%d" % abs(b)
    if abs(a) == abs(c) == 1 and a == c:
        return "merge_pm1"
    if abs(b) == abs(d) == 1 and b == d:
        return "merge_pm1"
    return "generic"


def nielsen_block_profile(word):
    """Block counts of the four Nielsen images of ``word`` (structural probe)."""
    from experiments.equivalence_classes.lib.words import apply_hom
    return [n_blocks(canon_rel(apply_hom(word, t))) for t in NIELSEN]


# --------------------------------------------------------------------------
# the three proved gates
# --------------------------------------------------------------------------

def gate_of(state):
    """Name of the first proved gate that accepts ``state``, or None.

    * ``terminal``      -- already a pair of distinct generators
    * ``two_block``     -- canonical_two_block_gate (the terminal mid_search uses)
    * ``one_occurrence``-- a relator with exactly one occurrence of a generator
                           and |abelian_det| == 1 (the forced hypothesis of T3)
    * ``bs_accept``     -- general consecutive-BS donor + accepting preflight
    """
    s = tuple(state)
    if len(s[0]) == 1 and len(s[1]) == 1 and s[0].lower() != s[1].lower():
        return "terminal"
    if canonical_two_block_gate(s):
        return "two_block"
    if any(one_occurrence_donor(w) for w in s) and abs(abelian_det(*s)) == 1:
        return "one_occurrence"
    if bs_gate(s, general=True) is not None and preflight(s).get("status") == "accept":
        return "bs_accept"
    return None


# --------------------------------------------------------------------------
# path analysis
# --------------------------------------------------------------------------

def parse_move(text):
    target, jsign, k1, k2 = (int(v) for v in text.split("_"))
    return target, jsign, k1, k2


def analyse(row):
    """One census row -> a record, or None when the root has no four-block relator."""
    root = canon_pair(*row["pair"])
    fb = [i for i, w in enumerate(root) if four_block_tuple(w) is not None]
    if not fb:
        return None
    index = fb[0]
    word = root[index]
    tup = four_block_tuple(word)
    other = root[1 - index]
    rec = {
        "name": row["name"],
        "route": row["route"],
        "nodes": row["nodes_explored"],
        "root": list(root),
        "fb_index": index,
        "fb_word": word,
        "fb_tuple": list(tup),
        "fb_canon": list(canon_tuple(tup)),
        "both_four_block": len(fb) == 2,
        "other_blocks": n_blocks(other),
        "fb_exp": list(exp_sums(word)),
        "other_exp": list(exp_sums(other)),
        "det": abelian_det(*root),
        "family": family_of(tup),
        "nielsen_blocks": nielsen_block_profile(word),
        "root_gate": gate_of(root),
    }
    if not row.get("solved") or "steps" not in row:
        rec["solved"] = False
        return rec
    rec["solved"] = True
    rec["n_steps"] = len(row["steps"])

    states = [tuple(s) for s in row["states"]]
    steps = row["steps"]

    # --- role of the four-block relator, step by step -------------------
    roles = []
    first_change = None
    donor_uses = 0
    aut_first = None
    for i, step in enumerate(steps):
        present = word in states[i]
        if step["kind"] == "automorphism":
            images = step["images"]
            k = NIELSEN.index(images)
            roles.append(f"A{k}")
            if present and first_change is None:
                first_change = i
                after = apply_pair((word, word), images)[0]   # image of the relator alone
                aut_first = {"map": k, "image": after, "blocks": n_blocks(after),
                             "image_tuple": four_block_tuple(after)}
            continue
        target, jsign, _k1, _k2 = parse_move(step["move"])
        tgt = states[i][target - 1]
        don = states[i][2 - target]
        if present and tgt == word:
            roles.append("T")
            if first_change is None:
                first_change = i
        elif present and don == word:
            roles.append("D")
            if first_change is None:
                donor_uses += 1
        elif present:
            roles.append("?")
        else:
            roles.append("-")
    rec["roles"] = "".join(roles)
    rec["first_change"] = first_change
    rec["donor_uses_before_change"] = donor_uses
    rec["aut_first"] = aut_first
    rec["kinds"] = "".join("A" if s["kind"] == "automorphism" else "S" for s in steps)

    # --- first state a proved gate closes -------------------------------
    gate_index, gate_name = None, None
    for i, s in enumerate(states[:GATE_SCAN_DEPTH + 1]):
        g = gate_of(s)
        if g is not None:
            gate_index, gate_name = i, g
            break
    rec["gate_index"] = gate_index
    rec["gate_name"] = gate_name
    if gate_index is not None:
        rec["macro"] = "".join(roles[:gate_index])
        rec["gate_state"] = list(states[gate_index])
    # terminal gate of the whole path (the census winner, cheaply re-derived)
    rec["final_state"] = list(states[-1])
    return rec


# --------------------------------------------------------------------------
# driver
# --------------------------------------------------------------------------

def main(argv):
    limit = int(argv[1]) if len(argv) > 1 else None
    files = sorted(glob.glob(ROWS_GLOB))
    if limit:
        files = files[:limit]
    if not files:
        raise SystemExit(f"no shards matched {ROWS_GLOB}")

    total = 0
    fb_rows = 0
    by_route = Counter()
    by_route_all = Counter()
    tuples = Counter()
    tuples_solved = Counter()
    exps = Counter()
    other_blocks = Counter()
    both_fb = 0
    roles_first = Counter()
    first_change_hist = Counter()
    donor_use_hist = Counter()
    aut_image_blocks = Counter()
    aut_image_gate = Counter()
    gate_hist = Counter()
    gate_by_index = Counter()
    macro_gate = Counter()
    macro_examples = defaultdict(list)
    det_hist = Counter()
    nblocks_pair = Counter()
    unsolved_fb = 0

    for fn in files:
        with open(fn) as fh:
            for line in fh:
                row = json.loads(line)
                total += 1
                by_route_all[(row["route"], row["solved"])] += 1
                rec = analyse(row)
                if rec is None:
                    continue
                nblocks_pair[tuple(sorted(n_blocks(w) for w in rec["root"]))] += 1
                if not rec["solved"]:
                    unsolved_fb += 1
                    continue
                fb_rows += 1
                by_route[rec["route"]] += 1
                tup = tuple(rec["fb_canon"])
                tuples[tup] += 1
                tuples_solved[tup] += 1
                exps[tuple(rec["fb_exp"])] += 1
                other_blocks[rec["other_blocks"]] += 1
                det_hist[rec["det"]] += 1
                both_fb += int(rec["both_four_block"])
                roles_first[rec["roles"][:1] or "(none)"] += 1
                first_change_hist[rec["first_change"]] += 1
                donor_use_hist[rec["donor_uses_before_change"]] += 1
                if rec["aut_first"]:
                    aut_image_blocks[rec["aut_first"]["blocks"]] += 1
                gate_hist[rec["gate_name"]] += 1
                if rec["gate_name"] is not None:
                    gate_by_index[(rec["gate_name"], rec["gate_index"])] += 1
                    key = (rec["gate_name"], rec["macro"])
                    macro_gate[key] += 1
                    if len(macro_examples[key]) < MAX_EXAMPLES_PER_PATTERN:
                        macro_examples[key].append(rec)

    def top(counter, n=40):
        return [[list(k) if isinstance(k, tuple) else k, v]
                for k, v in counter.most_common(n)]

    out = {
        "shards": len(files),
        "rows_scanned": total,
        "solved_rows_with_four_block_root": fb_rows,
        "unsolved_rows_with_four_block_root": unsolved_fb,
        "by_route": dict(by_route),
        "by_route_all_rows": {f"{r}|{s}": v for (r, s), v in by_route_all.items()},
        "block_profile_of_pair": top(nblocks_pair, 30),
        "both_relators_four_block": both_fb,
        "companion_block_count": dict(other_blocks),
        "det": dict(det_hist),
        "canonical_tuples_top": top(tuples, 60),
        "n_distinct_canonical_tuples": len(tuples),
        "exponent_sums_top": top(exps, 40),
        "first_role": dict(roles_first),
        "first_change_step": {str(k): v for k, v in sorted(first_change_hist.items(),
                                                           key=lambda kv: (kv[0] is None, kv[0]))},
        "donor_uses_before_change": {str(k): v for k, v in sorted(donor_use_hist.items())},
        "aut_image_block_count": {str(k): v for k, v in sorted(aut_image_blocks.items())},
        "gate_reached": {str(k): v for k, v in gate_hist.items()},
        "gate_by_index": [[list(k), v] for k, v in gate_by_index.most_common(60)],
        "macro_patterns": [[list(k), v] for k, v in macro_gate.most_common(60)],
    }
    with open(OUT_JSON, "w") as fh:
        json.dump(out, fh, indent=1, sort_keys=False)
    with open(OUT_EXAMPLES, "w") as fh:
        for key, recs in sorted(macro_examples.items(), key=lambda kv: -macro_gate[kv[0]]):
            for rec in recs:
                fh.write(json.dumps({"pattern": list(key), "count": macro_gate[key], **rec}) + "\n")
    print(json.dumps({k: v for k, v in out.items()
                      if k not in ("canonical_tuples_top", "macro_patterns", "gate_by_index")},
                     indent=1)[:4000])
    print("\ntop canonical (a,b,c,d):")
    for k, v in tuples.most_common(25):
        print("  ", k, v)
    print("\ntop macro patterns (gate, roles-before-gate):")
    for k, v in macro_gate.most_common(25):
        print("  ", k, v)
    print("\nwrote", OUT_JSON, "and", OUT_EXAMPLES)


if __name__ == "__main__":
    main(sys.argv)
