"""Mine the AC19 census certificates for FOUR-BLOCK roots.

A *four-block* cyclic relator is a cyclically reduced word with exactly four
maximal generator runs, i.e. ``y^a x^b y^c x^d`` with ``a,b,c,d != 0`` (two
y-blocks and two x-blocks).  The residual audit
(``research/residual_20260909/THEOREMS_PROOFS_AND_FREQUENCY.md`` section 6)
identifies this as the largest structural family left unsolved: 293 of the 727
residual roots carry such a relator.

This script answers Task A of the four-block brief against the *solved* part of
the frozen census
``results/heuristic_search/ac19_final_policy_full_1k/rows_*.jsonl`` (read-only):

  * how many solved roots carry a four-block relator, by route;
  * the distribution of the exponent patterns (a,b,c,d) modulo the symmetry
    group generated by block rotation, inversion, x<->y relabelling and the two
    sign flips (32 elements, see ``ORBIT_GENERATORS``);
  * how the certified path treats the four-block relator: donor or target,
    steps until it changes, what an ambient Nielsen map does to it;
  * the shortest prefix of the path that reaches a state one of the three
    proved gates closes (two-block unimodular / one-occurrence primitive /
    consecutive-BS with an accepting preflight), and the most frequent 2-4
    step macro patterns that bridge a four-block root to such a gate.

Nothing under ``research/supermoves_20260908/``, ``results/`` or ``data/`` is
written.  No search is run: only the saved states/steps are replayed with
``words.replay_move`` and O(length) recognizers are evaluated.

Usage:
    PYTHONPATH=. python3 research/residual_20260909/theory/FOURBLOCK_mine.py
    PYTHONPATH=. python3 research/residual_20260909/theory/FOURBLOCK_mine.py 5   # 5 shards only
"""
from __future__ import annotations

import glob
import json
import os
import sys
from collections import Counter, defaultdict

from experiments.equivalence_classes.lib.words import (
    abelian_det, apply_pair, canon_pair, canon_rel, exp_sums, replay_move,
)
from experiments.search.heuristic_1k import NIELSEN
from research.supermoves_20260908.bs_preflight import preflight
from research.supermoves_20260908.cheap_gates import (
    bs_gate, canonical_two_block_gate, one_occurrence_donor, two_block_gate,
)

ROWS_GLOB = "results/heuristic_search/ac19_final_policy_full_1k/rows_*.jsonl"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT_JSON = os.path.join(HERE, "FOURBLOCK_mine.json")
OUT_EXAMPLES = os.path.join(HERE, "FOURBLOCK_examples.jsonl")

GATE_SCAN_DEPTH = 8          # how many leading states of each path we gate-test
MAX_EXAMPLES_PER_PATTERN = 3


# --------------------------------------------------------------------------
# block structure
# --------------------------------------------------------------------------

def blocks(word):
    """Maximal cyclic runs of ``word`` as [(generator, signed exponent), ...].

    ``word`` must be cyclically reduced (canon_rel output is).  For a word using
    both generators the result starts at a block boundary, so the list is the
    cyclic block sequence read from an arbitrary but deterministic origin.
    """
    if not word:
        return []
    lowers = {c.lower() for c in word}
    if len(lowers) == 1:
        sign = 1 if word[0].islower() else -1
        return [(word[0].lower(), sign * len(word))]
    start = next(i for i in range(len(word)) if word[i].lower() != word[i - 1].lower())
    rotated = word[start:] + word[:start]
    out = []
    gen, count = rotated[0].lower(), 0
    for c in rotated:
        g, s = c.lower(), (1 if c.islower() else -1)
        if g == gen:
            count += s
        else:
            out.append((gen, count))
            gen, count = g, s
    out.append((gen, count))
    return out


def four_block_tuple(word):
    """(a,b,c,d) with the word read as y^a x^b y^c x^d, or None.

    The returned tuple starts at a y-block; it is one of the two rotations of
    the block cycle that do so, chosen deterministically (the first in
    ``blocks`` order).
    """
    bl = blocks(word)
    if len(bl) != 4:
        return None
    if bl[0][0] == "x":
        bl = bl[1:] + bl[:1]
    return (bl[0][1], bl[1][1], bl[2][1], bl[3][1])


def n_blocks(word):
    return len(blocks(word))


# --------------------------------------------------------------------------
# the symmetry group on exponent 4-tuples
# --------------------------------------------------------------------------

def _tau(t):                      # x <-> y relabelling, then rotate to a y-block
    a, b, c, d = t
    return (b, c, d, a)


def _iota(t):                     # relator inversion
    a, b, c, d = t
    return (-c, -b, -a, -d)


def _flip_x(t):                   # x -> X
    a, b, c, d = t
    return (a, -b, c, -d)


def _flip_y(t):                   # y -> Y
    a, b, c, d = t
    return (-a, b, -c, d)


ORBIT_GENERATORS = (_tau, _iota, _flip_x, _flip_y)


def orbit(t):
    seen = {tuple(t)}
    frontier = [tuple(t)]
    while frontier:
        cur = frontier.pop()
        for g in ORBIT_GENERATORS:
            nxt = g(cur)
            if nxt not in seen:
                seen.add(nxt)
                frontier.append(nxt)
    return seen


def canon_tuple(t):
    """Lexicographically least member of the symmetry orbit of ``t``."""
    return min(orbit(t))


def family_of(t):
    """Symmetry-invariant family label of a four-block exponent tuple.

    ``ey = a+c`` and ``ex = b+d`` are the relator's exponent sums; the unordered
    pair {|ey|,|ex|} is invariant under the whole symmetry group, and |det| = 1
    forces gcd(|ey|,|ex|) = 1.

      bs_stable_s<k>  one exponent sum vanishes: the relator is
                      t u^p t^-1 u^q with t = <generator>^k a *stable power*
                      (k = 1 is exactly the consecutive-BS donor shape of T5,
                      whose consecutivity |p+q| = 1 is then forced by det = 1)
      merge_pm1       the two blocks of one generator are both +-1 and have the
                      SAME sign: a single Nielsen map merges them (see theory)
      generic         everything else
    """
    a, b, c, d = t
    ey, ex = a + c, b + d
    if ey == 0:
        return "bs_stable_s%d" % abs(a)
    if ex == 0:
        return "bs_stable_s%d" % abs(b)
    if abs(a) == abs(c) == 1 and a == c:
        return "merge_pm1"
    if abs(b) == abs(d) == 1 and b == d:
        return "merge_pm1"
    return "generic"


_ORBIT_CACHE = {}


def orbit_class(word, cap=200000):
    """Aut(F2)-orbit class of a cyclic word: minimal cyclic length and the least
    block count attained at that length.

    Explores the four Nielsen maps and the three signed permutations under a
    non-increasing cyclic-length rule (Whitehead: a non-minimal word always has
    a strictly reducing elementary move in this set for F2), and reports

        'primitive'          minimal length 1
        'two_block:<w>'      minimal length attained by a two-block word w
        'irreducible_<k>b'   minimal length attained only with k >= 4 blocks
    """
    key = canon_rel(word)
    if key in _ORBIT_CACHE:
        return _ORBIT_CACHE[key]
    from experiments.equivalence_classes.lib.words import apply_hom
    maps = list(NIELSEN) + [{"x": "y", "y": "x"}, {"x": "X", "y": "y"}, {"x": "x", "y": "Y"}]
    best = len(key)
    seen = {key}
    frontier = [key]
    n = 0
    while frontier and n < cap:
        nxt = []
        for u in frontier:
            if len(u) > best:
                continue
            for t in maps:
                image = canon_rel(apply_hom(u, t))
                n += 1
                if len(image) > best or image in seen:
                    continue
                seen.add(image)
                nxt.append(image)
                best = min(best, len(image))
        frontier = nxt
    reps = [u for u in seen if len(u) == best]
    b = min(n_blocks(u) for u in reps)
    witness = min((u for u in reps if n_blocks(u) == b), key=lambda w: (len(w), w))
    out = ("primitive" if best == 1 else
           "two_block:%s" % witness if b <= 2 else "irreducible_%db" % b)
    _ORBIT_CACHE[key] = out
    return out


def nielsen_block_profile(word):
    """Block counts of the four Nielsen images of ``word`` (structural probe)."""
    from experiments.equivalence_classes.lib.words import apply_hom
    return [n_blocks(canon_rel(apply_hom(word, t))) for t in NIELSEN]


# --------------------------------------------------------------------------
# the three proved gates
# --------------------------------------------------------------------------

def gate_of(state):
    """Name of the first proved gate that accepts ``state``, or None.

    * ``terminal``      -- already a pair of distinct generators
    * ``two_block``     -- canonical_two_block_gate (the terminal mid_search uses)
    * ``one_occurrence``-- a relator with exactly one occurrence of a generator
                           and |abelian_det| == 1 (the forced hypothesis of T3)
    * ``bs_accept``     -- general consecutive-BS donor + accepting preflight
    """
    s = tuple(state)
    if len(s[0]) == 1 and len(s[1]) == 1 and s[0].lower() != s[1].lower():
        return "terminal"
    if canonical_two_block_gate(s):
        return "two_block"
    if any(one_occurrence_donor(w) for w in s) and abs(abelian_det(*s)) == 1:
        return "one_occurrence"
    if bs_gate(s, general=True) is not None and preflight(s).get("status") == "accept":
        return "bs_accept"
    return None


# --------------------------------------------------------------------------
# path analysis
# --------------------------------------------------------------------------

def parse_move(text):
    target, jsign, k1, k2 = (int(v) for v in text.split("_"))
    return target, jsign, k1, k2


def analyse(row):
    """One census row -> a record, or None when the root has no four-block relator."""
    root = canon_pair(*row["pair"])
    fb = [i for i, w in enumerate(root) if four_block_tuple(w) is not None]
    if not fb:
        return None
    index = fb[0]
    word = root[index]
    tup = four_block_tuple(word)
    other = root[1 - index]
    rec = {
        "name": row["name"],
        "route": row["route"],
        "nodes": row["nodes_explored"],
        "root": list(root),
        "fb_index": index,
        "fb_word": word,
        "fb_tuple": list(tup),
        "fb_canon": list(canon_tuple(tup)),
        "both_four_block": len(fb) == 2,
        "other_blocks": n_blocks(other),
        "fb_exp": list(exp_sums(word)),
        "other_exp": list(exp_sums(other)),
        "det": abelian_det(*root),
        "family": family_of(tup),
        "nielsen_blocks": nielsen_block_profile(word),
        "orbit_class": orbit_class(word),
        "root_gate": gate_of(root),
    }
    if not row.get("solved") or "steps" not in row:
        rec["solved"] = False
        return rec
    rec["solved"] = True
    rec["n_steps"] = len(row["steps"])

    states = [tuple(s) for s in row["states"]]
    steps = row["steps"]

    # --- role of the four-block relator, step by step -------------------
    roles = []
    shapes = []
    first_change = None
    donor_uses = 0
    aut_first = None
    for i, step in enumerate(steps):
        present = word in states[i]
        if step["kind"] == "automorphism":
            images = step["images"]
            k = NIELSEN.index(images)
            roles.append(f"A{k}")
            shapes.append("aut")
            if present and first_change is None:
                first_change = i
                after = apply_pair((word, word), images)[0]   # image of the relator alone
                aut_first = {"map": k, "image": after, "blocks": n_blocks(after),
                             "image_tuple": four_block_tuple(after)}
            continue
        target, jsign, k1, k2 = parse_move(step["move"])
        shapes.append("%s%s%s" % ("+" if jsign > 0 else "-",
                                  "0" if k1 == 0 else "r", "0" if k2 == 0 else "r"))
        tgt = states[i][target - 1]
        don = states[i][2 - target]
        if present and tgt == word:
            roles.append("T")
            if first_change is None:
                first_change = i
        elif present and don == word:
            roles.append("D")
            if first_change is None:
                donor_uses += 1
        elif present:
            roles.append("?")
        else:
            roles.append("-")
    rec["roles"] = "".join(roles)
    rec["shapes"] = shapes
    rec["donor_uses_total"] = roles.count("D")
    rec["target_uses_total"] = roles.count("T")
    rec["survives_to_end"] = word in states[-1]
    rec["first_change"] = first_change
    rec["donor_uses_before_change"] = donor_uses
    rec["aut_first"] = aut_first
    rec["kinds"] = "".join("A" if s["kind"] == "automorphism" else "S" for s in steps)

    # --- first state a proved gate closes -------------------------------
    gate_index, gate_name = None, None
    for i, s in enumerate(states[:GATE_SCAN_DEPTH + 1]):
        g = gate_of(s)
        if g is not None:
            gate_index, gate_name = i, g
            break
    rec["gate_index"] = gate_index
    rec["gate_name"] = gate_name
    if gate_index is not None:
        rec["macro"] = "".join(roles[:gate_index])
        rec["macro_shapes"] = "|".join(shapes[:gate_index])
        rec["gate_state"] = list(states[gate_index])
        rec["prefix"] = [{"state": list(states[i]),
                          "step": steps[i].get("move") or steps[i].get("images"),
                          "kind": steps[i]["kind"], "role": roles[i]}
                         for i in range(gate_index)]
    # terminal gate of the whole path (the census winner, cheaply re-derived)
    rec["final_state"] = list(states[-1])
    return rec


# --------------------------------------------------------------------------
# driver
# --------------------------------------------------------------------------

def gate_probe(pair, width=3, depth=2, cap=3000):
    """Deterministic bounded probe: keep the ``width`` shortest substitution
    children at each level and test the three proved gates.

    Charges one unit per generated child, so the whole probe on one row is
    bounded by ``cap`` units.  Returns (gate name, depth, units) or
    (None, None, units).
    """
    from experiments.equivalence_classes.lib.words import replay_move as rm
    root = canon_pair(*pair)
    level = [root]
    units = 0
    g = gate_of(root)
    if g:
        return g, 0, units
    for d in range(1, depth + 1):
        children = {}
        for state in level:
            for target in (1, 2):
                for jsign in (1, -1):
                    for k1 in range(len(state[target - 1])):
                        for k2 in range(len(state[2 - target])):
                            if units >= cap:
                                return None, None, units
                            units += 1
                            child = rm(state, (target, jsign, k1, k2))
                            key = tuple(child)
                            if key not in children:
                                children[key] = sum(map(len, child))
        ranked = sorted(children, key=lambda k: (children[k], k))
        for state in ranked[:width]:
            g = gate_of(state)
            if g:
                return g, d, units
        level = ranked[:width]
    return None, None, units


def probe_mode(n_rows=40, width=3, depth=2):
    """Run the bounded probe on a few dozen rows: 20 census-solved four-block
    roots and every dev-panel row with a four-block relator (capped)."""
    import csv
    out = {"width": width, "depth": depth, "census": [], "dev": []}
    files = sorted(glob.glob(ROWS_GLOB))
    picked = 0
    for fn in files[:3]:
        for line in open(fn):
            row = json.loads(line)
            if not row["solved"]:
                continue
            p = canon_pair(*row["pair"])
            fb = [w for w in p if four_block_tuple(w) is not None]
            if not fb or gate_of(p) is not None:
                continue
            if picked % 37:
                picked += 1
                continue
            picked += 1
            g, d, u = gate_probe(p, width, depth)
            out["census"].append({"name": row["name"], "pair": list(p),
                                  "family": family_of(four_block_tuple(fb[0])),
                                  "gate": g, "depth": d, "units": u,
                                  "census_nodes": row["nodes_explored"]})
            if len(out["census"]) >= n_rows // 2:
                break
        if len(out["census"]) >= n_rows // 2:
            break
    with open("research/residual_20260909/panels/dev.csv") as fh:
        for r in csv.DictReader(fh):
            p = canon_pair(r["r1"], r["r2"])
            fb = [w for w in p if four_block_tuple(w) is not None]
            if not fb:
                continue
            if len(out["dev"]) >= n_rows // 2:
                break
            g, d, u = gate_probe(p, width, depth)
            out["dev"].append({"name": r["name"], "pair": list(p),
                               "family": family_of(four_block_tuple(fb[0])),
                               "gate": g, "depth": d, "units": u})
    out["census_hits"] = sum(1 for r in out["census"] if r["gate"])
    out["dev_hits"] = sum(1 for r in out["dev"] if r["gate"])
    return out


def main(argv):
    if "--probe" in argv:
        res = probe_mode()
        path = os.path.join(HERE, "FOURBLOCK_probe.json")
        with open(path, "w") as fh:
            json.dump(res, fh, indent=1)
        print(json.dumps({k: v for k, v in res.items() if k not in ("census", "dev")},
                         indent=1))
        for tag in ("census", "dev"):
            print("--", tag)
            for r in res[tag]:
                print("  ", r)
        print("wrote", path)
        return
    limit = int(argv[1]) if len(argv) > 1 else None
    files = sorted(glob.glob(ROWS_GLOB))
    if limit:
        files = files[:limit]
    if not files:
        raise SystemExit(f"no shards matched {ROWS_GLOB}")

    agg = {
        "total": 0, "fb_solved": 0, "fb_unsolved": 0, "both_fb": 0,
        "by_route": Counter(), "by_route_all": Counter(),
        "nblocks_pair": Counter(), "family": Counter(), "family_route": Counter(),
        "tuples": Counter(), "tuples_by_family": defaultdict(Counter),
        "expsums": Counter(), "expsums_by_family": Counter(),
        "companion_blocks": Counter(), "det": Counter(),
        "first_role": Counter(), "first_change": Counter(),
        "donor_uses": Counter(), "aut_image_blocks": Counter(),
        "gate": Counter(), "gate_family": Counter(), "gate_index": Counter(),
        "macro": Counter(), "root_gate": Counter(), "shape1": Counter(),
        "macro_shape": Counter(),
        "nielsen_min_blocks": Counter(), "nielsen_min_by_family": Counter(),
        "orbit_class": Counter(), "orbit_family": Counter(), "orbit_gate": Counter(),
        "survives": Counter(), "donor_total": Counter(),
        "steps_hist": Counter(),
    }
    macro_examples = defaultdict(list)
    fam_examples = defaultdict(list)

    for fn in files:
        with open(fn) as fh:
            for line in fh:
                row = json.loads(line)
                agg["total"] += 1
                agg["by_route_all"][(row["route"], row["solved"])] += 1
                rec = analyse(row)
                if rec is None:
                    continue
                agg["nblocks_pair"][tuple(sorted(n_blocks(w) for w in rec["root"]))] += 1
                if not rec["solved"]:
                    agg["fb_unsolved"] += 1
                    continue
                fam = rec["family"]
                agg["fb_solved"] += 1
                agg["by_route"][rec["route"]] += 1
                agg["family"][fam] += 1
                agg["family_route"][(fam, rec["route"])] += 1
                tup = tuple(rec["fb_canon"])
                agg["tuples"][tup] += 1
                agg["tuples_by_family"][fam][tup] += 1
                ey, ex = rec["fb_exp"][1], rec["fb_exp"][0]
                agg["expsums"][tuple(sorted((abs(ex), abs(ey))))] += 1
                agg["expsums_by_family"][(fam, tuple(sorted((abs(ex), abs(ey)))))] += 1
                agg["companion_blocks"][rec["other_blocks"]] += 1
                agg["det"][rec["det"]] += 1
                agg["both_fb"] += int(rec["both_four_block"])
                agg["first_role"][(fam, rec["roles"][:1] or ".")] += 1
                agg["first_change"][(fam, rec["first_change"])] += 1
                agg["donor_uses"][(fam, min(rec["donor_uses_before_change"], 9))] += 1
                agg["steps_hist"][(fam, min(rec["n_steps"] // 10 * 10, 60))] += 1
                if rec["aut_first"]:
                    agg["aut_image_blocks"][(fam, rec["aut_first"]["blocks"])] += 1
                mn = min(rec["nielsen_blocks"])
                agg["nielsen_min_blocks"][mn] += 1
                agg["nielsen_min_by_family"][(fam, mn)] += 1
                oc = rec["orbit_class"]
                agg["orbit_class"][oc] += 1
                agg["orbit_family"][(fam, oc)] += 1
                agg["orbit_gate"][(oc, rec["gate_name"])] += 1
                agg["survives"][(fam, rec["survives_to_end"])] += 1
                agg["donor_total"][(fam, min(rec["donor_uses_total"], 12))] += 1
                agg["root_gate"][(fam, rec["root_gate"])] += 1
                agg["shape1"][(fam, rec["shapes"][0] if rec["shapes"] else ".")] += 1
                agg["gate"][(fam, rec["gate_name"])] += 1
                if rec["gate_name"] is not None:
                    agg["gate_index"][(fam, rec["gate_name"], rec["gate_index"])] += 1
                    key = (fam, rec["gate_name"], rec["macro"])
                    agg["macro"][key] += 1
                    if 1 <= rec["gate_index"] <= 4:
                        agg["macro_shape"][(rec["gate_name"], rec["macro_shapes"])] += 1
                    if len(macro_examples[key]) < MAX_EXAMPLES_PER_PATTERN:
                        macro_examples[key].append(rec)
                if len(fam_examples[fam]) < 6 and rec["root_gate"] is None:
                    fam_examples[fam].append(rec)

    def dump(counter, n=None):
        items = counter.most_common(n) if n else sorted(counter.items(), key=lambda kv: -kv[1])
        return [["|".join(map(str, k)) if isinstance(k, tuple) else str(k), v] for k, v in items]

    out = {
        "shards": len(files),
        "rows_scanned": agg["total"],
        "solved_rows_with_four_block_root": agg["fb_solved"],
        "unsolved_rows_with_four_block_root": agg["fb_unsolved"],
        "both_relators_four_block": agg["both_fb"],
        "by_route": dict(agg["by_route"]),
        "by_route_all_rows": dump(agg["by_route_all"]),
        "block_profile_of_pair": dump(agg["nblocks_pair"], 30),
        "family": dict(agg["family"]),
        "family_by_route": dump(agg["family_route"]),
        "companion_block_count": {str(k): v for k, v in sorted(agg["companion_blocks"].items())},
        "det": {str(k): v for k, v in agg["det"].items()},
        "n_distinct_canonical_tuples": len(agg["tuples"]),
        "canonical_tuples_top": dump(agg["tuples"], 60),
        "canonical_tuples_by_family": {f: dump(c, 25) for f, c in agg["tuples_by_family"].items()},
        "abs_exponent_sums": dump(agg["expsums"], 30),
        "abs_exponent_sums_by_family": dump(agg["expsums_by_family"], 40),
        "nielsen_min_image_blocks": {str(k): v for k, v in sorted(agg["nielsen_min_blocks"].items())},
        "nielsen_min_image_blocks_by_family": dump(agg["nielsen_min_by_family"]),
        "orbit_class": dump(agg["orbit_class"], 40),
        "orbit_class_by_family": dump(agg["orbit_family"], 40),
        "orbit_class_by_gate": dump(agg["orbit_gate"], 40),
        "four_block_survives_to_end": dump(agg["survives"]),
        "donor_uses_total_by_family": dump(agg["donor_total"], 40),
        "root_gate_by_family": dump(agg["root_gate"]),
        "first_role_by_family": dump(agg["first_role"]),
        "first_change_step_by_family": dump(agg["first_change"], 60),
        "donor_uses_before_change_by_family": dump(agg["donor_uses"], 60),
        "aut_first_image_blocks_by_family": dump(agg["aut_image_blocks"]),
        "steps_hist_by_family": dump(agg["steps_hist"], 60),
        "gate_reached_by_family": dump(agg["gate"]),
        "gate_index_by_family": dump(agg["gate_index"], 80),
        "macro_patterns": dump(agg["macro"], 120),
        "first_move_shape_by_family": dump(agg["shape1"], 40),
        "macro_move_shapes_len1to4": dump(agg["macro_shape"], 40),
    }
    with open(OUT_JSON, "w") as fh:
        json.dump(out, fh, indent=1, sort_keys=False)
    with open(OUT_EXAMPLES, "w") as fh:
        for key, recs in sorted(macro_examples.items(), key=lambda kv: -agg["macro"][kv[0]]):
            for rec in recs:
                fh.write(json.dumps({"kind": "macro", "pattern": list(key),
                                     "count": agg["macro"][key], **rec}) + "\n")
        for fam, recs in sorted(fam_examples.items()):
            for rec in recs:
                fh.write(json.dumps({"kind": "family_example", "pattern": [fam], **rec}) + "\n")
    for k in ("rows_scanned", "solved_rows_with_four_block_root",
              "unsolved_rows_with_four_block_root", "both_relators_four_block",
              "by_route", "family", "nielsen_min_image_blocks"):
        print(k, "=", out[k])
    print("\nroot_gate_by_family:", out["root_gate_by_family"][:14])
    print("\ntop canonical tuples:", out["canonical_tuples_top"][:12])
    print("\ntop macros:", out["macro_patterns"][:20])
    print("\nwrote", OUT_JSON, "and", OUT_EXAMPLES)


if __name__ == "__main__":
    main(sys.argv)
