"""W1: finite AC-graph decision for the MMS02 bridge over A5.

Bridge target (docs/AK3_PROMISE_LEDGER.md route 1, .scratch/mms02_u_xy_bridge.md):

    (A, B, zYX)  ~AC(1-3)  (A, B, Xyz)   in F(x,y,z),

with A = xzYXyxZXYxyZ, B = XyxZXYXyxzXYxy (uppercase = inverse).

Soundness of the test (proved in fable/proofs/W1_BRIDGE_FINITE_TEST.md): for any
homomorphism phi: F(x,y,z) -> G with phi(A) = phi(B) = 1, an AC1-AC3 path between
the two triples forces their images (1,1,phi(zYX)) and (1,1,phi(Xyz)) into one
orbit of the move action on G^3 generated by
    inv(i):        t_i <- t_i^{-1}
    conj(i,c):     t_i <- c t_i c^{-1},          c in H := <phi x, phi y, phi z>
    mult(i,j,s,c): t_i <- t_i * (c t_j^s c^{-1}), j != i, s in {+1,-1}, c in H.
Every AC1-AC3 move maps into a composition of these (left-multiplications and row
swaps are derived moves; entries always stay in H).

This is a COMPLETE finite closure (exact BFS over at most |A5|^3 = 216,000
states), not a node-budgeted search.

Positive control: (A,B,zYX) is certified AC-trivial (134 primitive moves,
.scratch/mms02_u_xy_bridge.md), so the orbit of (1,1,phi(zYX)) MUST contain
(phi x, phi y, phi z). A control failure means the move model is wrong; no
negative may be read in that case.

Decision per hom: does the same orbit contain (1,1,phi(Xyz))?
  - NO for any phi  => the bridge is refuted (exact certificate).
  - YES for all phi => the A5 obstruction is blind for the full bridge.

Usage:
  python3 a5_bridge_orbit.py scan          # enumerate homs, group by conjugacy
  python3 a5_bridge_orbit.py bfs INDEX     # decide one hom class
  python3 a5_bridge_orbit.py all           # scan + decide every class + digest
"""
from __future__ import annotations

import hashlib
import itertools
import json
import sys

import numpy as np
from numba import njit

WORD_A = "xzYXyxZXYxyZ"
WORD_B = "XyxZXYXyxzXYxy"
WORD_KXY = "zYX"
WORD_KPUB = "Xyz"

# ---------------------------------------------------------------- group tables


def build_a5():
    perms = [p for p in itertools.permutations(range(5)) if _is_even(p)]
    perms.sort()
    assert len(perms) == 60
    index = {p: i for i, p in enumerate(perms)}
    mult = np.empty((60, 60), dtype=np.int32)
    inv = np.empty(60, dtype=np.int32)
    for i, p in enumerate(perms):
        q = [0] * 5
        for k in range(5):
            q[p[k]] = k
        inv[i] = index[tuple(q)]
        for j, r in enumerate(perms):
            # (p*r)(k) = p(r(k)): apply r first, then p.
            mult[i, j] = index[tuple(p[r[k]] for k in range(5))]
    e = index[tuple(range(5))]
    assert all(mult[i, inv[i]] == e for i in range(60))
    return perms, mult, inv, e


def _is_even(p):
    inv_count = sum(
        1
        for a in range(5)
        for b in range(a + 1, 5)
        if p[a] > p[b]
    )
    return inv_count % 2 == 0


def eval_word(word, gx, gy, gz, mult, inv, e):
    val = e
    table = {"x": gx, "y": gy, "z": gz}
    for ch in word:
        g = table[ch.lower()]
        if ch.isupper():
            g = inv[g]
        val = mult[val, g]
    return int(val)


# ---------------------------------------------------------------- hom scanning


@njit(cache=True)
def _scan(mult, inv, e, word_a, word_b):
    """Return all (X,Y,Z) in A5^3 with A(X,Y,Z) = B(X,Y,Z) = identity.

    word encoding: signed generator ids; +1/-1 = x/X, +2/-2 = y/Y, +3/-3 = z/Z.
    """
    out = np.empty((216000, 3), dtype=np.int32)
    n = 0
    for gx in range(60):
        for gy in range(60):
            for gz in range(60):
                ok = True
                for word in (word_a, word_b):
                    val = e
                    for s in word:
                        if s == 1:
                            g = gx
                        elif s == -1:
                            g = inv[gx]
                        elif s == 2:
                            g = gy
                        elif s == -2:
                            g = inv[gy]
                        elif s == 3:
                            g = gz
                        else:
                            g = inv[gz]
                        val = mult[val, g]
                    if val != e:
                        ok = False
                        break
                if ok:
                    out[n, 0] = gx
                    out[n, 1] = gy
                    out[n, 2] = gz
                    n += 1
    return out[:n]


def encode_word(word):
    m = {"x": 1, "y": 2, "z": 3}
    return np.array(
        [m[c.lower()] * (-1 if c.isupper() else 1) for c in word],
        dtype=np.int32,
    )


def subgroup_elements(gens, mult, e):
    seen = {e}
    frontier = [e]
    while frontier:
        nxt = []
        for h in frontier:
            for g in gens:
                v = int(mult[h, g])
                if v not in seen:
                    seen.add(v)
                    nxt.append(v)
        frontier = nxt
    return sorted(seen)


def conj_classes_of_homs(homs, mult, inv):
    """Group hom triples by simultaneous conjugation; return one rep per class."""
    canon = {}
    for gx, gy, gz in homs:
        best = None
        for g in range(60):
            gi = inv[g]
            t = (
                int(mult[mult[g, gx], gi]),
                int(mult[mult[g, gy], gi]),
                int(mult[mult[g, gz], gi]),
            )
            if best is None or t < best:
                best = t
        canon.setdefault(best, []).append((int(gx), int(gy), int(gz)))
    reps = sorted(canon)
    return reps, {r: len(canon[r]) for r in reps}


# ------------------------------------------------------------------ BFS orbit


@njit(cache=True)
def _bfs(mult, inv, h_elems, start0, start1, start2):
    visited = np.zeros(216000, dtype=np.uint8)
    queue = np.empty(216000, dtype=np.int32)
    start = start0 * 3600 + start1 * 60 + start2
    visited[start] = 1
    queue[0] = start
    head = 0
    tail = 1
    nh = h_elems.shape[0]
    t = np.empty(3, dtype=np.int32)
    while head < tail:
        s = queue[head]
        head += 1
        t[0] = s // 3600
        t[1] = (s // 60) % 60
        t[2] = s % 60
        for i in range(3):
            old = t[i]
            # inversion
            t[i] = inv[old]
            ns = t[0] * 3600 + t[1] * 60 + t[2]
            if visited[ns] == 0:
                visited[ns] = 1
                queue[tail] = ns
                tail += 1
            # conjugation and multiplications
            for ci in range(nh):
                c = h_elems[ci]
                cinv = inv[c]
                # conj(i, c)
                t[i] = mult[mult[c, old], cinv]
                ns = t[0] * 3600 + t[1] * 60 + t[2]
                if visited[ns] == 0:
                    visited[ns] = 1
                    queue[tail] = ns
                    tail += 1
                # mult(i, j, s, c) for both partners and signs
                for j in range(3):
                    if j == i:
                        continue
                    gj = t[j] if j != i else 0
                    for sgn in range(2):
                        g = gj if sgn == 0 else inv[gj]
                        factor = mult[mult[c, g], cinv]
                        t[i] = mult[old, factor]
                        ns = t[0] * 3600 + t[1] * 60 + t[2]
                        if visited[ns] == 0:
                            visited[ns] = 1
                            queue[tail] = ns
                            tail += 1
            t[i] = old
    return visited, tail


# ---------------------------------------------------------------------- main


def run_scan(perms, mult, inv, e, verbose=True):
    homs = _scan(mult, inv, e, encode_word(WORD_A), encode_word(WORD_B))
    reps, sizes = conj_classes_of_homs(homs.tolist(), mult, inv)
    nontrivial = [r for r in reps if r != (e, e, e)]
    if verbose:
        print(f"homs total: {len(homs)}  conjugacy classes: {len(reps)}")
        for r in reps:
            print(f"  class rep {r}  size {sizes[r]}")
        print(f"nontrivial classes: {len(nontrivial)}")
    return reps, sizes


def run_bfs(rep, perms, mult, inv, e, verbose=True):
    gx, gy, gz = rep
    h = np.array(
        subgroup_elements([gx, gy, gz], mult, e), dtype=np.int32
    )
    kxy = eval_word(WORD_KXY, gx, gy, gz, mult, inv, e)
    kpub = eval_word(WORD_KPUB, gx, gy, gz, mult, inv, e)
    visited, orbit = _bfs(mult, inv, h, e, e, kxy)
    control = bool(visited[gx * 3600 + gy * 60 + gz])
    decision = bool(visited[e * 3600 + e * 60 + kpub])
    record = {
        "rep": list(rep),
        "H_order": int(len(h)),
        "kxy": int(kxy),
        "kpub": int(kpub),
        "orbit_size": int(orbit),
        "control_contains_trivializer": control,
        "same_orbit_as_kpub": decision,
    }
    if verbose:
        print(json.dumps(record))
    return record


def main(argv):
    perms, mult, inv, e = build_a5()
    cmd = argv[1] if len(argv) > 1 else "all"
    if cmd == "scan":
        run_scan(perms, mult, inv, e)
        return 0
    if cmd == "bfs":
        reps, _ = run_scan(perms, mult, inv, e, verbose=False)
        rep = reps[int(argv[2])]
        run_bfs(rep, perms, mult, inv, e)
        return 0
    # all
    reps, sizes = run_scan(perms, mult, inv, e)
    records = []
    for rep in reps:
        if rep == (e, e, e):
            continue
        records.append(run_bfs(rep, perms, mult, inv, e))
    blob = json.dumps(records, sort_keys=True).encode()
    print(f"record digest sha256: {hashlib.sha256(blob).hexdigest()}")
    bad_control = [r for r in records if not r["control_contains_trivializer"]]
    refuted = [
        r
        for r in records
        if r["control_contains_trivializer"] and not r["same_orbit_as_kpub"]
    ]
    if bad_control:
        print("CONTROL FAILURE: move model unsound; no conclusion.")
        return 2
    if refuted:
        print("BRIDGE REFUTED over A5 by hom classes:")
        for r in refuted:
            print(f"  {r['rep']}")
        return 1
    print("A5 obstruction BLIND for the full bridge (all hom classes connect).")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
