"""W5 — invariant battery for the MMS02 bridge  (A,B,zYX) =?= (A,B,Xyz).

Probes, each with a control that can fail:

  I1  ABELIANISATION.  Both triples give unimodular 3x3 integer matrices;
      an explicit elementary chain (adds + negations only, i.e. literal AC
      moves) is produced and verified.  Control: (x,y,z) vs (x,y,zz) has
      |det| 1 vs 2 and the reducer must REFUSE.

  I2  FOX / ALEXANDER over R = Z[F3^ab] = Z[t1^,t2^,t3^].
      (a) self-test: the fundamental identity  sum_k d_k(w)(t_k - 1) = t^ab(w) - 1.
      (b) exact transformation law of the Jacobian under an AC2 move
              row_i' = row_i + t^{a_i}(1 - t^{e a_j}) d(w) + unit * row_j,
          verified on random moves.  The middle term ("junk") is the whole
          obstruction to a Fox invariant: it lies in the augmentation ideal I
          and is generally nonzero.
      (c) the ideal generated by all achievable junk is I itself, because
          (a_A, a_B, a_K) is a Z-basis of Z^3 (checked: |det| = 1); hence the
          largest quotient of R on which the Jacobian's row class is
          AC-invariant is R/I = Z, where it is the abelianised matrix -- I1,
          blind.
      (d) candidate invariant "det J up to units": computed for Txy, Tpub and
          the standard triple.  CERTIFIED-POSITIVE CONTROL: Txy is AC-trivial
          (134 primitive moves, repo certificate), so if det J(Txy) is not a
          unit the candidate is refuted as an AC invariant.

Run:
  python3 scripts/run_proof_guarded.py --timeout-seconds 60 -- \
      python3 fable/proofs/checkers/bridge_invariant_probe.py
"""

from __future__ import annotations

import itertools
import json
import os
import random
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from w5_words import (  # noqa: E402
    A, B, K_PUB, K_XY, abelianize, apply_ac2, inv, reduce_word,
)
from w5_linalg import (  # noqa: E402
    apply_ops_to_matrix, det3, eye, invert_ops, reduce_to_identity,
)

FAILS: list[str] = []
Poly = dict[tuple[int, int, int], int]


def check(name: str, cond: bool, detail: str = "") -> None:
    print(f"{'PASS' if cond else 'FAIL'}  {name}" + (f"   {detail}" if detail else ""))
    if not cond:
        FAILS.append(name)


# ------------------------------------------------------------- Laurent ring --

def p_zero() -> Poly:
    return {}


def p_mono(exp: tuple[int, int, int], c: int = 1) -> Poly:
    return {exp: c} if c else {}


def p_add(*ps: Poly) -> Poly:
    out: Poly = {}
    for p in ps:
        for k, v in p.items():
            out[k] = out.get(k, 0) + v
            if out[k] == 0:
                del out[k]
    return out


def p_neg(p: Poly) -> Poly:
    return {k: -v for k, v in p.items()}


def p_mul(p: Poly, q: Poly) -> Poly:
    out: Poly = {}
    for k1, v1 in p.items():
        for k2, v2 in q.items():
            k = (k1[0] + k2[0], k1[1] + k2[1], k1[2] + k2[2])
            out[k] = out.get(k, 0) + v1 * v2
            if out[k] == 0:
                del out[k]
    return out


def p_aug(p: Poly) -> int:
    """Evaluate at t = (1,1,1)."""
    return sum(p.values())


def p_is_unit(p: Poly) -> bool:
    return len(p) == 1 and abs(next(iter(p.values()))) == 1


def p_str(p: Poly) -> str:
    if not p:
        return "0"
    terms = []
    for k in sorted(p):
        c = p[k]
        m = "".join(f"t{i+1}^{k[i]}" for i in range(3) if k[i])
        terms.append(f"{c:+d}" + (f"*{m}" if m else ""))
    return " ".join(terms)


def unit_equal(p: Poly, q: Poly) -> bool:
    """p = +- t^a * q for some monomial t^a ?"""
    if len(p) != len(q) or not p:
        return p == q
    kp, kq = min(p), min(q)
    for sign in (1, -1):
        shift = tuple(kp[i] - kq[i] for i in range(3))
        cand = {tuple(k[i] + shift[i] for i in range(3)): sign * v for k, v in q.items()}
        if cand == p:
            return True
    return False


def diag_unit_equal(p: dict[int, int], q: dict[int, int]) -> bool:
    if len(p) != len(q) or not p:
        return p == q
    shift = min(p) - min(q)
    for sign in (1, -1):
        if {k + shift: sign * v for k, v in q.items()} == p:
            return True
    return False


def p_specialise_diag(p: Poly) -> dict[int, int]:
    """t1 = t2 = t3 = t  (the cyclic Alexander specialisation)."""
    out: dict[int, int] = {}
    for k, v in p.items():
        d = k[0] + k[1] + k[2]
        out[d] = out.get(d, 0) + v
        if out[d] == 0:
            del out[d]
    return out


# --------------------------------------------------------------- Fox calculus --

def fox(w: str) -> list[Poly]:
    """(d w / d x1, d w / d x2, d w / d x3) over Z[F3^ab]."""
    ders = [p_zero(), p_zero(), p_zero()]
    pref = [0, 0, 0]
    for c in w:
        k = "xyz".index(c.lower())
        if c.islower():
            ders[k] = p_add(ders[k], p_mono(tuple(pref)))  # type: ignore[arg-type]
            pref[k] += 1
        else:
            pref[k] -= 1
            ders[k] = p_add(ders[k], p_mono(tuple(pref), -1))  # type: ignore[arg-type]
    return ders


def jac(T: tuple[str, str, str]) -> list[list[Poly]]:
    return [fox(r) for r in T]


def det_poly(J: list[list[Poly]]) -> Poly:
    total = p_zero()
    for perm in itertools.permutations(range(3)):
        sgn = 1
        pl = list(perm)
        for i in range(3):
            for j in range(i + 1, 3):
                if pl[i] > pl[j]:
                    sgn = -sgn
        term = p_mono((0, 0, 0))
        for i in range(3):
            term = p_mul(term, J[i][perm[i]])
        total = p_add(total, term if sgn == 1 else p_neg(term))
    return total


def ab_matrix(T: tuple[str, str, str]) -> list[list[int]]:
    return [list(abelianize(r)) for r in T]


def main() -> int:
    Txy = (A, B, K_XY)
    Tpub = (A, B, K_PUB)
    STD = ("x", "y", "z")
    rng = random.Random(20260828)

    # ================================================================= I1 ====
    Mxy, Mpub = ab_matrix(Txy), ab_matrix(Tpub)
    print("abelianised matrices")
    print("  Txy :", Mxy, " det", det3(Mxy))
    print("  Tpub:", Mpub, " det", det3(Mpub))
    check("I1: both abelianised matrices are unimodular",
          abs(det3(Mxy)) == 1 and abs(det3(Mpub)) == 1)

    ops_pub = reduce_to_identity(Mpub)
    ops_xy = reduce_to_identity(Mxy)
    ok = ops_pub is not None and ops_xy is not None
    check("I1: both reduce to the identity by adds+negations", ok)
    chain = None
    if ok:
        chain = list(ops_pub) + invert_ops(list(ops_xy))  # type: ignore[arg-type]
        got = apply_ops_to_matrix(Mpub, chain)
        check("I1: explicit elementary chain carries Ab(Tpub) to Ab(Txy)",
              got == Mxy, f"{len(chain)} elementary ops")
    # control: must be able to fail
    Mbad = ab_matrix(("x", "y", "zz"))
    check("I1 control(-): (x,y,zz) has |det| = 2 and the reducer refuses",
          abs(det3(Mbad)) == 2 and reduce_to_identity(Mbad) is None)

    # ================================================================= I2 ====
    # (a) fundamental identity, on many words
    words = [A, B, K_XY, K_PUB, "xyzXYZ", "XXyzzZY", ""]
    for _ in range(30):
        words.append(reduce_word("".join(rng.choice("xyzXYZ") for _ in range(rng.randint(1, 14)))))
    ok = True
    for w in words:
        d = fox(w)
        lhs = p_zero()
        for k in range(3):
            e = [0, 0, 0]
            e[k] = 1
            lhs = p_add(lhs, p_mul(d[k], p_add(p_mono(tuple(e)), p_mono((0, 0, 0), -1))))
        rhs = p_add(p_mono(abelianize(w)), p_mono((0, 0, 0), -1))
        ok &= (lhs == rhs)
    check("I2a: Fox fundamental identity holds on 37 words", ok)

    # (b) transformation law under an AC2 move, on random moves
    law_ok, junk_seen, junk_aug_ok = True, 0, True
    junk_witness = None
    for _ in range(40):
        T = rng.choice([Txy, Tpub])
        i, j = rng.sample(range(3), 2)
        e = rng.choice([1, -1])
        w = reduce_word("".join(rng.choice("xyzXYZ") for _ in range(rng.randint(0, 4))))
        T2 = apply_ac2(T, i, j, e, w)
        J1, J2 = jac(T), jac(T2)
        a_i, a_j, a_w = abelianize(T[i]), abelianize(T[j]), abelianize(w)
        one = p_mono((0, 0, 0))
        junk_scal = p_mul(p_mono(a_i), p_add(one, p_mono(tuple(x * e for x in a_j), -1)))
        dw = fox(w)
        if e == 1:
            donor_scal = p_mono(tuple(a_i[k] + a_w[k] for k in range(3)))
        else:
            donor_scal = p_mono(tuple(a_i[k] + a_w[k] - a_j[k] for k in range(3)), -1)
        for col in range(3):
            pred = p_add(J1[i][col], p_mul(junk_scal, dw[col]), p_mul(donor_scal, J1[j][col]))
            law_ok &= (pred == J2[i][col])
        for col in range(3):
            if p_mul(junk_scal, dw[col]):
                junk_seen += 1
                junk_aug_ok &= (p_aug(p_mul(junk_scal, dw[col])) == 0)
                if junk_witness is None:
                    junk_witness = (T is Txy and "Txy" or "Tpub", i, j, e, w,
                                    p_str(p_mul(junk_scal, dw[col])))
    check("I2b: Jacobian transformation law verified on 40 random AC2 moves", law_ok)
    check("I2b: every junk term lies in the augmentation ideal (aug = 0)", junk_aug_ok)
    check("I2b: junk is nonzero on the bridge triples (invariance really fails)",
          junk_seen > 0, f"{junk_seen} nonzero junk entries; witness {junk_witness}")

    # (c) the junk ideal is the augmentation ideal
    exps = [abelianize(A), abelianize(B), abelianize(K_XY)]
    check("I2c: (a_A, a_B, a_K) is a Z-basis of Z^3, so (1 - t^a) generate I",
          abs(det3([list(v) for v in exps])) == 1)

    # (d) det J up to units, with the certified-positive control
    dets = {}
    for name, T in (("Txy", Txy), ("Tpub", Tpub), ("std", STD)):
        d = det_poly(jac(T))
        dets[name] = d
        print(f"  det J({name:4s}) = {p_str(d)}")
        print(f"      aug = {p_aug(d)}   #terms = {len(d)}   "
              f"diagonal t-specialisation = {sorted(p_specialise_diag(d).items())}")
    check("I2d: det J(std) = 1", dets["std"] == p_mono((0, 0, 0)))
    check("I2d: det J augments to +-1 on both bridge triples",
          abs(p_aug(dets["Txy"])) == 1 and abs(p_aug(dets["Tpub"])) == 1)
    txy_unit = p_is_unit(dets["Txy"])
    check("I2d control(+): Txy is CERTIFIED AC-trivial, so an AC-invariant "
          "'det J up to units' would force det J(Txy) to be a unit",
          not txy_unit,
          "det J(Txy) is NOT a unit -> candidate invariant REFUTED (as expected)"
          if not txy_unit else "det J(Txy) IS a unit -> candidate survives this control")
    check("I2d: det J(Txy) is not a unit multiple of det J(Tpub) in the full "
          "3-variable ring", not unit_equal(dets["Txy"], dets["Tpub"]))

    # (e) the cyclic (t1=t2=t3) specialisation: the classical Alexander datum
    DELTA = {0: 1, 1: -3, 2: 5, 3: -3, 4: 1}          # t^4 - 3t^3 + 5t^2 - 3t + 1
    dxy, dpub = p_specialise_diag(dets["Txy"]), p_specialise_diag(dets["Tpub"])
    check("I2e: both diagonal specialisations equal +-t^k * (t^4-3t^3+5t^2-3t+1), "
          "the Delta recorded in .scratch/mms02_bridge_alexander_filter.md",
          diag_unit_equal(dxy, DELTA) and diag_unit_equal(dpub, DELTA))
    check("I2e: the two diagonal specialisations agree up to a unit -- the "
          "cyclic Alexander datum is BLIND to the bridge",
          diag_unit_equal(dxy, dpub))

    out = {
        "ab_matrices": {"Txy": Mxy, "Tpub": Mpub},
        "elementary_chain_len": len(chain) if chain else None,
        "elementary_chain": chain,
        "det_J": {k: {" ".join(map(str, kk)): vv for kk, vv in v.items()}
                  for k, v in dets.items()},
        "det_J_str": {k: p_str(v) for k, v in dets.items()},
        "det_J_diag": {k: sorted(p_specialise_diag(v).items()) for k, v in dets.items()},
        "junk_witness": junk_witness,
    }
    dest = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "out", "w5_invariant_probe.json")
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, "w") as fh:
        json.dump(out, fh, indent=1)
    print(f"\nwrote {dest}")
    print("\n" + ("ALL CHECKS PASS" if not FAILS else f"FAILURES: {FAILS}"))
    return 1 if FAILS else 0


if __name__ == "__main__":
    raise SystemExit(main())
