"""W2h: layer-1 liveness on the 23 census chains with [Q : Gamma] = infinite.

W2G_G_STRATUM_DEATH.md proves that for the 44 census chains with
[Q : Gamma] < infinity (Gamma = <R, U, w> <= Q = C2 * Z) the full-module
image satisfies  sum_i L_i M = ker(eps)  -- the double-coset invariant d
is 1 at every window -- so no layer-1 death certificate can exist there.
Its section 7 leaves the other 23 chains open: Gamma\\Q is infinite, so
W2g's Lemma 3 (a finite loop over the permutation group P induced by Q on
the finite set Gamma\\Q) does not apply.

THIS CHECKER CLOSES THAT GAP.  Three ingredients.

(1) THE SPACE.  Gamma\\Q is the completed Stallings graph: the finite
    folded core, plus one infinite cone hanging at every missing slot.  A
    vertex is (u, w) with u a core state and w a reduced escape word over
    {c, t, T}; w = () is a core vertex.  Reading a letter from a cone
    vertex is free reduction of w against that letter, so the cones are
    exactly the cones of the Cayley tree of Q (which IS a tree, Q being a
    free product of C2 and Z).  Omega = Gamma\\Q/<c> is the set of c-orbits
    of that graph -- infinite, but with this finite description.

(2) THE OPERATORS' IMAGE, EXACTLY.  W2g's Lemma 2 (telescoping) needs no
    finiteness: M / (L2 + L3 + L4)M = Z[Omega] is free on Omega, and the
    L2, L3, L4 columns die there.  What is new here is that the L0 and L1
    columns collapse to a SIGNED SUM OVER A FIXED FINITE STATE TUPLE.
    Using  X = h2 S h2^-1 in Gamma,  U in Gamma,  R in Gamma  and the
    defect identity  U^-1 h3 S h3^-1 = w in Q  (w in Gamma):

        pi(L1 e_v) = [w(sigma(h2 b) . v)] + [w(sigma(h3 b) . v)]
                   - [w(sigma(h2)   . v)] - [w(sigma(h3)   . v)],  b = S^-1 B

        pi(L0 e_v) = [w(sigma(R)  . v)] + [w(sigma(h2 R) . v)] + [w(sigma(h3 R) . v)]
                   - [w(sigma(A)  . v)] - [w(sigma(h2 A) . v)] - [w(sigma(h3 A) . v)]

    with sigma(x) = Gamma x the state of x, "." the right Q-action on
    Gamma\\Q, and w(.) the Omega-class.  Every coefficient is +-1 and the
    dependence on v is ONLY through the right action on a 4- (resp. 6-)
    element state tuple.  That is the exact form of "the operators have
    finite support, so far-out tree classes are hit in a translation-
    invariant pattern".  It is an ALGEBRAIC FIAT and is guarded by an
    EFFECTIVE control (--mode identity): the sigma-tuple row must equal the
    row obtained by tracing every term of the operator that
    build_operators_general actually returns, and corrupting one operator
    term must break the equality.

(3) THE DECISION.  Let A = the subgroup of Z[Omega] generated by all those
    rows.  Then  D in sum_i L_i M  <=>  pi(D) in A, and A = Z[Omega]_0
    (augmentation zero) is the infinite-index form of "d = 1".  Both are
    decided by exact integer (Hermite) linear algebra on the rows with
    |v| <= L; membership is CONSTRUCTIVE (an explicit integer combination,
    re-multiplied out and compared term by term).  The coverage obeys an
    exact margin law: every Omega-class at depth <= L - mu carries
    [w] - [w_base] in A, with mu constant in L.

MODES
  identity   effective control for (2): sigma-tuple rows vs direct operator
             rows on both the finite- and infinite-index chains; the
             L2/L3/L4 rows must vanish identically; corrupting a term must
             break both.  Also pins the base coset (sigma(R) = sigma(U) =
             sigma(w) = base) -- the W2g defect.
  finite     the extended machinery run in its FINITE specialization on the
             44 finite-index chains; d and image_is_ker_eps must reproduce
             out/w2g_omega_all.json exactly.
  image      main mode: per infinite-index chain, the margin law and
             pi(D) in A over Z with a verified witness.
  lift       constructive: solve D + sum_i L_i x_i = 0 over Z directly in
             the module (a rho-hop system, no Omega machinery), and verify
             with the unmodified apply_operator; a corrupted operator must
             leave a residual.
  probe      positive control: on a SYNTHETIC system (L0, L1 doubled) the
             invariant is 2 by construction; a primitive Omega-difference
             defect must then be certified NOT in the image, the doubled
             one must be, and the independent one-hop solver must agree
             mod 2.  A detector that cannot fire is not evidence.
  period     the window axes: the action of the centralizer generators
             zeta2, zeta3 on the completed graph, and the (k0, k1) box.

EXIT CODES
  0  run completed with every control green (any verdict is a RESULT).
  2  a control failed -- the run is void.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from math import gcd
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[2]))
sys.path.insert(0, str(HERE))

_ARGV = list(sys.argv)
sys.argv = sys.argv[:1]
import g_stratum_death as GS  # noqa: E402
sys.argv = _ARGV

from experiments.stable_ac.depth4_period_two_lift_certificate import (  # noqa
    add_vectors,
    apply_operator,
    c_vertex,
    quotient_inverse,
    quotient_multiply,
    quotient_reduce,
)

PS, LV = GS.PS, GS.LV
C, T = LV.C, LV.T
OMEGA_JSON = HERE / "out" / "w2g_omega_all.json"
PRIMES = (2, 3, 5)
INV = {"c": "c", "t": "T", "T": "t"}


# ------------------------------------------------------------ words


def wstr(tup):
    """LV letter tuple -> reduced word over {'c','t','T'}."""
    return "".join("c" if abs(l) == C else ("t" if l == T else "T")
                   for l in tup)


def reduced_words(maxlen):
    """Every reduced word over {c,t,T} (no cc, tT, Tt) of length <= maxlen."""
    yield ""
    frontier = [""]
    for _ in range(maxlen):
        nxt = []
        for w in frontier:
            for x in "ctT":
                if w and x == INV[w[-1]]:
                    continue
                nxt.append(w + x)
                yield w + x
        frontier = nxt


# -------------------------------------------- completed Schreier graph


class Completed:
    """Gamma\\Q as core + cones.  Vertex = (core index, reduced escape word).

    The folded core is a partial Q-graph; every missing slot is completed by
    an infinite cone of the Cayley tree of Q.  Reading a letter inside a cone
    is free reduction of the escape word, so the completion is exact and
    finite to describe.  Works verbatim when the core is already complete
    (then no vertex ever leaves it) -- that is the finite specialization.
    """

    def __init__(self, folded):
        f = folded
        st = f.states()
        ix = {s: i for i, s in enumerate(st)}
        self.n_core = len(st)
        # base coset Gamma*1 -- pinned, never assumed to be index 0
        self.base = (ix[f.find(0)], ())
        self.pc = [ix[f.find(f.cm[s])] if s in f.cm else None for s in st]
        self.pt = [ix[f.find(f.tout[s])] if s in f.tout else None for s in st]
        self.pT = [ix[f.find(f.tin[s])] if s in f.tin else None for s in st]
        self.finite = all(x is not None
                          for x in self.pc + self.pt + self.pT)

    def step(self, y, x):
        u, esc = y
        if not esc:
            tgt = {"c": self.pc, "t": self.pt, "T": self.pT}[x][u]
            return (u, (x,)) if tgt is None else (tgt, ())
        if x == INV[esc[-1]]:
            return (u, esc[:-1])
        return (u, esc + (x,))

    def walk(self, y, word):
        for x in word:
            y = self.step(y, x)
        return y

    def trace(self, word):
        return self.walk(self.base, word)

    def omega(self, y):
        """the c-orbit {y, y.c}, named by its shallower member."""
        p = self.step(y, "c")
        return min(y, p, key=lambda z: (len(z[1]), z[0], z[1]))


def depth(cls):
    return len(cls[1])


# ---------------------------------------- the sigma-tuple row identity


def sigma_terms(chain, h):
    """{i: [(group element, sign)]} realising pi(L_i e_v) -- see module docstring."""
    R, S, _U = chain
    qR, qS = GS.q(R), GS.q(S)
    qA = quotient_reduce(LV.SOURCE_A)
    qB = quotient_reduce(LV.SOURCE_B)
    h2, h3 = GS.q(h[2]), GS.q(h[3])
    beta = quotient_multiply(quotient_inverse(qS), qB)
    return {
        0: [(qR, +1),
            (quotient_multiply(h2, qR), +1),
            (quotient_multiply(h3, qR), +1),
            (qA, -1),
            (quotient_multiply(h2, qA), -1),
            (quotient_multiply(h3, qA), -1)],
        1: [(quotient_multiply(h2, beta), +1),
            (quotient_multiply(h3, beta), +1),
            (h2, -1),
            (h3, -1)],
    }


def sigma_states(cp, chain, h):
    return {i: [(cp.trace(wstr(gw)), a) for gw, a in terms]
            for i, terms in sigma_terms(chain, h).items()}


def row_sigma(cp, states_i, v):
    row = {}
    for s, a in states_i:
        om = cp.omega(cp.walk(s, v))
        row[om] = row.get(om, 0) + a
    return {k: a for k, a in row.items() if a}


def row_direct(cp, op, v):
    """Omega-row of the column L_i e_v, straight off the operator."""
    row = {}
    for gw, a in op.items():
        om = cp.omega(cp.trace(wstr(gw) + v))
        row[om] = row.get(om, 0) + a
    return {k: a for k, a in row.items() if a}


# ------------------------------------------- exact integer row lattice


def _lin(a, u, b, v):
    out = {}
    for k, x in u.items():
        y = a * x
        if y:
            out[k] = y
    for k, x in v.items():
        y = out.get(k, 0) + b * x
        if y:
            out[k] = y
        elif k in out:
            del out[k]
    return out


def _egcd(a, b):
    if b == 0:
        return (abs(a), 1 if a >= 0 else -1, 0)
    old_r, r = a, b
    old_s, s = 1, 0
    old_t, t = 0, 1
    while r:
        qq = old_r // r
        old_r, r = r, old_r - qq * r
        old_s, s = s, old_s - qq * s
        old_t, t = t, old_t - qq * t
    if old_r < 0:
        old_r, old_s, old_t = -old_r, -old_s, -old_t
    return old_r, old_s, old_t


class ZEchelon:
    """Hermite-style echelon of a lattice of sparse integer vectors.

    Exact over Z (not a mod-p or rational shadow): membership answers
    "is this vector an INTEGER combination of the rows added so far".
    Combination coefficients are tracked so every positive answer ships a
    witness that is re-multiplied out and compared term by term.
    """

    def __init__(self, order=None):
        self.piv = {}
        self.order = order or (lambda c: c)

    def _key(self, v):
        return min(v, key=self.order)

    def add(self, vec, tag):
        v = {k: a for k, a in vec.items() if a}
        c = {tag: 1}
        while v:
            col = self._key(v)
            if col not in self.piv:
                if v[col] < 0:
                    v = _lin(-1, v, 0, {})
                    c = _lin(-1, c, 0, {})
                self.piv[col] = (v, c)
                return
            pr, pc = self.piv[col]
            a, b = v[col], pr[col]
            if a % b == 0:
                f = a // b
                v = _lin(1, v, -f, pr)
                c = _lin(1, c, -f, pc)
            else:
                gg, x, y = _egcd(b, a)
                nr = _lin(x, pr, y, v)
                nc = _lin(x, pc, y, c)
                f1, f2 = b // gg, a // gg
                v = _lin(f1, v, -f2, pr)
                c = _lin(f1, c, -f2, pc)
                self.piv[col] = (nr, nc)

    def member(self, vec):
        v = {k: a for k, a in vec.items() if a}
        c = {}
        while v:
            col = self._key(v)
            if col not in self.piv:
                return False, None
            pr, pc = self.piv[col]
            if v[col] % pr[col]:
                return False, None
            f = v[col] // pr[col]
            v = _lin(1, v, -f, pr)
            c = _lin(1, c, -f, pc)
        return True, {k: -a for k, a in c.items()}


DEEP_FIRST = (lambda c: (-len(c[1]), c[0], c[1]))


# ------------------------------------------------------------ helpers


def chain_setup(row, window=(0, 0, 0, 0), k=0):
    ch = tuple(row["chain"])
    g = row["g_gen"]
    cp = Completed(GS.Folded(GS.gamma_gens(ch, g)))
    sl = PS.chain_slots_g(ch, g, max(k, abs(window[0]), abs(window[1])),
                          max(k, abs(window[0]), abs(window[1])))
    ops, defect, h = GS.window_data(ch, g, sl, window)
    return ch, g, cp, ops, defect, h, sl


def defect_image(cp, defect):
    out = {}
    for vtx, cf in defect.items():
        om = cp.omega(cp.trace(wstr(vtx)))
        out[om] = out.get(om, 0) + cf
    return {k: a for k, a in out.items() if a}


def winv(w):
    return "".join(INV[x] for x in reversed(w))


def word_family(cp, states, L, align=0):
    """The reduced words v the rows are taken over.

    The ball of radius L, plus -- when `align` > 0 -- the ALIGNED family
    `winv(escape word of a state) + u`, |u| <= align.  A state sitting at
    depth D in a cone is only ever brought back to the core by a v whose
    first D letters spell its escape word backwards, so a plain ball of
    radius L < D carries no row in which that entry is shallow.  Every
    aligned word is an ordinary element of Q, so the rows it contributes are
    ordinary elements of the lattice: aligning changes which certificates
    are FOUND, never which are VALID.
    """
    out = {v for v in reduced_words(L)}
    if align:
        for terms in states.values():
            for (u_core, esc), _a in terms:
                if not esc:
                    continue
                pref = winv("".join(esc))
                for u in reduced_words(align):
                    v = pref
                    for x in u:
                        v = v[:-1] if (v and x == INV[v[-1]]) else v + x
                    out.add(v)
    return sorted(out, key=lambda w: (len(w), w))


def build_rows(cp, states, L, align=0):
    """{(i, v): row} over the word family, deduped by row."""
    out, seen = {}, set()
    for v in word_family(cp, states, L, align):
        for i in (0, 1):
            row = row_sigma(cp, states[i], v)
            if not row:
                continue
            key = tuple(sorted(row.items()))
            if key in seen:
                continue
            seen.add(key)
            out[(i, v)] = row
    return out


def coverage(cp, Z, rows):
    """per-depth count of Omega-classes with [w] - [w_base] in the lattice."""
    om0 = cp.omega(cp.base)
    cls = {c for row in rows.values() for c in row}
    per = {}
    for c in cls:
        d = depth(c)
        ok = True if c == om0 else Z.member({c: 1, om0: -1})[0]
        a, b = per.get(d, (0, 0))
        per[d] = (a + int(ok), b + 1)
    full = -1
    for d in sorted(per):
        if per[d][0] == per[d][1]:
            full = d
        else:
            break
    return full, {str(d): list(per[d]) for d in sorted(per)}


# ------------------------------------------------------------- modes


def mode_identity(args, rows):
    """EFFECTIVE control for the sigma-tuple identity and for Lemma 2'."""
    sel = rows if not args.stratum_only else [r for r in rows if r["stratum"]]
    if args.chains:
        a, b = args.chains.split(":")
        sel = sel[int(a or 0):int(b or len(sel))]
    out, ok = [], True
    for r in sel:
        ch, g, cp, ops, defect, h, _sl = chain_setup(r)
        states = sigma_states(cp, ch, h)
        # base pinning: the generators of Gamma must trace to the base coset
        gens = [cp.trace(wstr(GS.q(x))) for x in GS.gamma_gens(ch, g)]
        base_ok = all(y == cp.base for y in gens)
        n_id, bad_id, n_van, bad_van = 0, 0, 0, 0
        for v in reduced_words(args.radius):
            for i in (0, 1):
                n_id += 1
                if row_sigma(cp, states[i], v) != row_direct(cp, ops[i], v):
                    bad_id += 1
            for i in (2, 3, 4):
                n_van += 1
                if row_direct(cp, ops[i], v):
                    bad_van += 1
        # corruption must break BOTH assertions
        bad_ops = list(ops)
        d1 = dict(bad_ops[1])
        d1.pop(sorted(d1)[0])
        bad_ops[1] = d1
        d2 = dict(bad_ops[2])
        d2.pop(sorted(d2)[0])
        bad_ops[2] = d2
        broke_id = any(row_sigma(cp, states[1], v)
                       != row_direct(cp, bad_ops[1], v)
                       for v in reduced_words(args.radius))
        broke_van = any(row_direct(cp, bad_ops[2], v)
                        for v in reduced_words(args.radius))
        rec = {"chain": r["chain"], "g": g,
               "finite_core": cp.finite, "n_core": cp.n_core,
               "base_pinned_gamma_gens_trace_to_base": base_ok,
               "identity_checks": n_id, "identity_mismatches": bad_id,
               "l234_row_checks": n_van, "l234_nonvanishing": bad_van,
               "corruption_breaks_identity": broke_id,
               "corruption_breaks_vanishing": broke_van}
        rec["passed"] = (base_ok and bad_id == 0 and bad_van == 0
                         and broke_id and broke_van)
        ok = ok and rec["passed"]
        out.append(rec)
        print(json.dumps(rec))
    summ = {"chains": len(out), "all_passed": ok and bool(out),
            "identity_checks": sum(o["identity_checks"] for o in out),
            "identity_mismatches": sum(o["identity_mismatches"] for o in out),
            "l234_row_checks": sum(o["l234_row_checks"] for o in out),
            "l234_nonvanishing": sum(o["l234_nonvanishing"] for o in out),
            "radius": args.radius}
    print(json.dumps({"summary": summ}))
    _dump(args, "identity", summ, out)
    return 0 if summ["all_passed"] else 2


def mode_finite(args, rows):
    """The extended machinery in its finite specialization vs W2g."""
    want = {}
    if OMEGA_JSON.exists():
        for rec in json.loads(OMEGA_JSON.read_text())["rows"]:
            if rec.get("gamma_index"):
                want[(tuple(rec["chain"]), rec["g"])] = rec
    out, ok = [], True
    for r in rows:
        ch, g, cp, ops, defect, h, _sl = chain_setup(r)
        if not cp.finite:
            continue
        states = sigma_states(cp, ch, h)
        rws = build_rows(cp, states, args.radius, args.align)
        d = 0
        for row in rws.values():
            for a in row.values():
                d = gcd(d, abs(a))
        om0 = cp.omega(cp.base)
        piD = defect_image(cp, defect)
        m = piD.get(om0, 0)
        n_omega = len({cp.omega((u, ())) for u in range(cp.n_core)})
        ref = want.get((ch, g))
        rec = {"chain": r["chain"], "g": g, "n_core": cp.n_core,
               "n_omega": n_omega, "d": d, "m": m,
               "image_is_ker_eps": d == 1,
               "w2g_d": ref["d"] if ref else None,
               "w2g_image_is_ker_eps": ref["image_is_ker_eps"] if ref else None,
               "w2g_n_omega": ref["n_omega"] if ref else None}
        rec["agrees_with_w2g"] = bool(
            ref and rec["d"] in ref["d"] and len(ref["d"]) == 1
            and rec["image_is_ker_eps"] == ref["image_is_ker_eps"]
            and rec["n_omega"] == ref["n_omega"])
        ok = ok and rec["agrees_with_w2g"]
        out.append(rec)
    summ = {"finite_index_chains": len(out),
            "reference_rows": len(want),
            "agree_with_w2g_omega_all": sum(1 for o in out
                                            if o["agrees_with_w2g"]),
            "d_values": sorted({o["d"] for o in out}),
            "image_is_ker_eps": sum(1 for o in out if o["image_is_ker_eps"]),
            "all_agree": ok and len(out) == len(want) and bool(out),
            "radius": args.radius}
    print(json.dumps({"summary": summ}))
    _dump(args, "finite", summ, out)
    return 0 if summ["all_agree"] else 2


def mode_image(args, rows):
    """Main mode: the margin law and pi(D) in A over Z, per chain."""
    sel = [r for r in rows if not Completed(
        GS.Folded(GS.gamma_gens(r["chain"], r["g_gen"]))).finite]
    if args.stratum_only:
        sel = [r for r in sel if r["stratum"]]
    if args.chains:
        a, b = args.chains.split(":")
        sel = sel[int(a or 0):int(b or len(sel))]
    Ls = [int(x) for x in args.radii.split(",")]
    out, ok = [], True
    for r in sel:
        ch, g, cp, ops, defect, h, _sl = chain_setup(r)
        states = sigma_states(cp, ch, h)
        piD = defect_image(cp, defect)
        rec = {"chain": r["chain"], "g": g, "live_one_hop": r["live"],
               "stratum": r["stratum"], "n_core": cp.n_core,
               "piD_augmentation": sum(piD.values()),
               "piD_classes": len(piD),
               "levels": []}
        for L in Ls:
            t0 = time.time()
            rws = build_rows(cp, states, L, args.align)
            Z = ZEchelon(order=DEEP_FIRST)
            for tag, row in rws.items():
                Z.add(row, tag)
            member, combo = Z.member(piD)
            verified = None
            if member:
                acc = {}
                for tag, cf in combo.items():
                    for k, a in rws[tag].items():
                        acc[k] = acc.get(k, 0) + cf * a
                verified = ({k: a for k, a in acc.items() if a} == piD)
            full, prof = coverage(cp, Z, rws)
            rec["levels"].append({
                "L": L, "rows": len(rws), "pivots": len(Z.piv),
                "unit_differences_up_to_depth": full,
                "margin": L - full,
                "piD_in_lattice_over_Z": member,
                "witness_terms": len(combo) if member else None,
                "witness_reverified": verified,
                "depth_profile": prof,
                "secs": round(time.time() - t0, 2)})
        margins = {lv["margin"] for lv in rec["levels"]}
        rec["margin_constant"] = len(margins) == 1
        rec["margin"] = sorted(margins)
        rec["coverage_growth"] = [[lv["L"], lv["unit_differences_up_to_depth"]]
                                  for lv in rec["levels"]]
        rec["coverage_depth"] = max(lv["unit_differences_up_to_depth"]
                                    for lv in rec["levels"])
        rec["piD_in_lattice_over_Z"] = any(
            lv["piD_in_lattice_over_Z"] for lv in rec["levels"])
        rec["witness_reverified"] = all(
            lv["witness_reverified"] for lv in rec["levels"]
            if lv["piD_in_lattice_over_Z"])
        rec["witness_terms"] = min(
            [lv["witness_terms"] for lv in rec["levels"]
             if lv["piD_in_lattice_over_Z"]] or [None])
        # the infinite-index form of "d = 1": every Omega-difference the
        # computation reaches lies in the lattice, and so does pi(D)
        rec["d_eff_is_1"] = (rec["piD_in_lattice_over_Z"]
                             and rec["witness_reverified"]
                             and rec["coverage_depth"] >= 1)
        ok = ok and rec["piD_augmentation"] == 0 and rec["witness_reverified"]
        out.append(rec)
        print(json.dumps({k: v for k, v in rec.items() if k != "levels"}))
    summ = {"chains": len(out),
            "radii": Ls,
            "piD_in_lattice_over_Z": sum(1 for o in out
                                         if o["piD_in_lattice_over_Z"]),
            "witnesses_reverified": sum(1 for o in out
                                        if o["witness_reverified"]),
            "margin_constant": sum(1 for o in out if o["margin_constant"]),
            "margins": sorted({m for o in out for m in o["margin"]}),
            "coverage_depth_min": min([o["coverage_depth"] for o in out]
                                      or [None]),
            "d_eff_is_1": sum(1 for o in out if o["d_eff_is_1"]),
            "with_death_certificate": sum(
                1 for o in out if not o["piD_in_lattice_over_Z"]),
            "controls_passed": ok and bool(out),
            "verdict": ("NO_DEATH_CERTIFICATE_AND_PROVABLY_LIVE"
                        if out and all(o["d_eff_is_1"] for o in out)
                        else "MIXED")}
    print(json.dumps({"summary": summ}))
    _dump(args, "image", summ, out)
    return 0 if summ["controls_passed"] else 2


def mode_lift(args, rows):
    """Explicit integral x with D + sum_i L_i x_i = 0, verified in M."""
    sel = [r for r in rows if not Completed(
        GS.Folded(GS.gamma_gens(r["chain"], r["g_gen"]))).finite]
    if args.chains:
        a, b = args.chains.split(":")
        sel = sel[int(a or 0):int(b or len(sel))]
    out, ok, mutated = [], True, False
    for r in sel:
        ch, g, cp, ops, defect, h, sl = chain_setup(r, k=args.k)
        for k0 in range(-args.k, args.k + 1):
            for k2 in range(-args.k, args.k + 1):
                ops_w, dfc, _h = GS.window_data(ch, g, sl, (k0, 0, k2, 0))
                sol = seeded_lift(cp, ch, _h, ops_w, dfc, args)
                rec = {"chain": r["chain"], "g": g, "window": [k0, 0, k2, 0],
                       "defect_terms": len(dfc), "rho": args.rho,
                       "variables": sol["variables"],
                       "route": sol.get("route"),
                       "solvable_over_Z": sol["ok"],
                       "x_terms": sol["x_terms"],
                       "residual_after_lift": sol["residual"],
                       "VERIFIED_layer1_solution": sol["ok"]
                       and sol["residual"] == 0}
                if sol["ok"] and not mutated:
                    bad = list(ops_w)
                    d4 = dict(bad[4])
                    d4.pop(sorted(d4)[0])
                    bad[4] = d4
                    still = verify(dfc, tuple(bad), sol["x"])
                    print(json.dumps({
                        "control": "mutation_breaks_verified_solution",
                        "residual_after_corruption": len(still),
                        "passed": bool(still)}))
                    ok = ok and bool(still)
                    mutated = True
                ok = ok and (not sol["ok"] or sol["residual"] == 0)
                out.append(rec)
                print(json.dumps(rec))
    summ = {"windows": len(out),
            "verified_layer1_solutions": sum(
                1 for o in out if o["VERIFIED_layer1_solution"]),
            "unsolved_at_rho": sum(1 for o in out if not o["solvable_over_Z"]),
            "mutation_control_run": mutated,
            "controls_passed": ok and bool(out)}
    print(json.dumps({"summary": summ}))
    _dump(args, "lift", summ, out)
    return 0 if summ["controls_passed"] else 2


def solve_module(ops, defect, rho):
    """D + sum_i L_i x_i = 0 over Z, variables from a rho-HOP expansion.

    W2b's `one_hop_system` is the rho = 1 case: variables (i, v) whose column
    L_i e_v meets supp(D).  Here the expansion is iterated rho times, so the
    truncation W2b/W2e/W2f inherit is relaxed rather than replaced by a
    radius ball (which wastes columns far from the defect).  A solution found
    at any rho is an exact solution of the untruncated equation.
    """
    return solve_module_from(ops, defect, rho, [], range(5))


def solve_module_from(ops, defect, rho, seed, which):
    """As solve_module, with extra seed variables and an operator subset."""
    frontier = set(defect)
    seen_v, variables = set(seed), list(seed)
    for (i, v) in seed:
        frontier.update(apply_operator(ops[i], {v: 1}))
    for _ in range(rho):
        if len(variables) > 40000:
            break
        new_v = []
        for i in which:
            op = ops[i]
            for gw in op:
                gi = quotient_inverse(gw)
                for u in frontier:
                    v = c_vertex(quotient_multiply(gi, u))
                    if (i, v) not in seen_v:
                        seen_v.add((i, v))
                        new_v.append((i, v))
        variables.extend(new_v)
        frontier = set()
        for (i, v) in new_v:
            frontier.update(apply_operator(ops[i], {v: 1}))
    Z = ZEchelon(order=lambda w: (-len(w), w))
    for (i, v) in variables:
        img = apply_operator(ops[i], {v: 1})
        if img:
            Z.add(img, (i, v))
    member, combo = Z.member({k: -a for k, a in defect.items()})
    if not member:
        return {"ok": False, "x": None, "x_terms": None,
                "variables": len(variables), "residual": None}
    x = [dict() for _ in range(5)]
    for (i, v), cf in combo.items():
        x[i][v] = x[i].get(v, 0) + cf
    return {"ok": True, "x": x, "x_terms": [len(xi) for xi in x],
            "variables": len(variables),
            "residual": len(verify(defect, ops, x))}


def seeded_lift(cp, ch, h, ops, defect, args):
    """Explicit x, seeded by the Omega witness.

    The Omega lattice decides D in sum_i L_i M and hands back an integer
    combination of L0/L1 columns; the residual then lies in
    ker(pi) = I_Gamma M = L2 M + L3 M + L4 M by Lemma 2, so only the
    telescoping operators are needed to finish it.  Seeding the module
    system with the witness's own columns is what makes the finish local.
    """
    states = sigma_states(cp, ch, h)
    rws = build_rows(cp, states, int(args.radii.split(",")[-1]), args.align)
    Z = ZEchelon(order=DEEP_FIRST)
    for tag, row in rws.items():
        Z.add(row, tag)
    member, combo = Z.member(defect_image(cp, defect))
    seed = []
    y = [dict() for _ in range(5)]
    if member:
        for (i, v), cf in combo.items():
            vv = c_vertex(LV.to_tuple(v))
            y[i][vv] = y[i].get(vv, 0) + cf
            seed.append((i, vv))
        resid = dict(defect)
        for i, yi in enumerate(y):
            if yi:
                resid = add_vectors(resid, apply_operator(
                    ops[i], {k: -a for k, a in yi.items()}))
        resid = {k: a for k, a in resid.items() if a}
        sol = solve_module_from(ops, resid, args.resid_rho or args.rho,
                                [], (2, 3, 4))
        print(json.dumps({"omega_witness_terms": len(combo),
                          "residual_terms_in_I_Gamma_M": len(resid),
                          "telescoping_solve": sol["ok"],
                          "telescoping_variables": sol["variables"]}))
        if sol["ok"]:
            x = [{k: -a for k, a in yi.items()} for yi in y]
            for i in (2, 3, 4):
                for k, a in sol["x"][i].items():
                    x[i][k] = x[i].get(k, 0) + a
            x = [{k: a for k, a in xi.items() if a} for xi in x]
            return {"ok": True, "x": x, "x_terms": [len(xi) for xi in x],
                    "variables": sol["variables"], "route": "omega_seeded",
                    "residual": len(verify(defect, ops, x))}
    out = solve_module(ops, defect, args.rho)
    out["route"] = "hop_expansion"
    return out


def verify(defect, ops, x):
    """D + sum L_i x_i with the unmodified certificate primitives."""
    acc = dict(defect)
    for i, xi in enumerate(x):
        if xi:
            acc = add_vectors(acc, apply_operator(ops[i], xi))
    return {k: v for k, v in acc.items() if v}


def mode_probe(args, rows):
    """POSITIVE control: the detector must be able to fire.

    On the real systems the lattice contains pi(D), so nothing can ever be
    certified dead -- a detector that never fires is not evidence.  So it is
    run on a SYNTHETIC system with L0, L1 doubled (L2, L3, L4 untouched),
    whose Omega-lattice is 2A by construction.  A PRIMITIVE Omega-difference
    defect must then be certified NOT in the image, its double must be, and
    the independent one-hop solver must agree that the primitive one is
    unsolvable mod 2.
    """
    sel = [r for r in rows if not Completed(
        GS.Folded(GS.gamma_gens(r["chain"], r["g_gen"]))).finite]
    if args.chains:
        a, b = args.chains.split(":")
        sel = sel[int(a or 0):int(b or len(sel))]
    out, ok, fired = [], True, 0
    for r in sel:
        ch, g, cp, ops, defect, h, _sl = chain_setup(r)
        states = sigma_states(cp, ch, h)
        L = int(args.radii.split(",")[0])
        rws = build_rows(cp, states, L, args.align)
        Z = ZEchelon(order=DEEP_FIRST)
        for tag, row in rws.items():
            Z.add(row, tag)
        piD = defect_image(cp, defect)
        real_ok = Z.member(piD)[0]
        # synthetic: doubled L0, L1 -> every row doubled -> lattice 2A
        Zs = ZEchelon(order=DEEP_FIRST)
        for tag, row in rws.items():
            Zs.add({k: 2 * a for k, a in row.items()}, tag)
        # a primitive Omega-difference: two module vertices in distinct classes
        pair = None
        for s in PS.ball(6):
            v1 = c_vertex(LV.to_tuple(s))
            o1 = cp.omega(cp.trace(wstr(v1)))
            for s2 in PS.ball(6):
                v2 = c_vertex(LV.to_tuple(s2))
                o2 = cp.omega(cp.trace(wstr(v2)))
                if o1 != o2 and Z.member({o1: 1, o2: -1})[0]:
                    pair = (v1, v2, o1, o2)
                    break
            if pair:
                break
        if pair is None:
            rec = {"chain": r["chain"], "g": g,
                   "status": "NO_PRIMITIVE_PAIR_FOUND", "passed": False}
            ok = False
            out.append(rec)
            print(json.dumps(rec))
            continue
        v1, v2, o1, o2 = pair
        odd = {o1: 1, o2: -1}
        even = {o1: 2, o2: -2}
        syn_ops = (LV.add_group_ring(ops[0], ops[0]),
                   LV.add_group_ring(ops[1], ops[1]),
                   ops[2], ops[3], ops[4])
        mod_defect = {v1: 1, v2: -1}
        rows_o, rhs_o, _ = LV.one_hop_system(mod_defect, syn_ops)
        rec = {"chain": r["chain"], "g": g,
               "real_piD_in_lattice": real_ok,
               "synthetic_primitive_in_lattice": Zs.member(odd)[0],
               "synthetic_double_in_lattice": Zs.member(even)[0],
               "one_hop_solvable_mod2": bool(
                   LV.solve_mod_p(rows_o, rhs_o, 2)),
               "primitive_in_real_lattice": Z.member(odd)[0]}
        rec["detector_fires_on_primitive"] = (
            not rec["synthetic_primitive_in_lattice"])
        rec["detector_silent_on_double"] = rec["synthetic_double_in_lattice"]
        rec["one_hop_agrees_primitive_dead_mod2"] = (
            rec["one_hop_solvable_mod2"] is False)
        rec["passed"] = (rec["detector_fires_on_primitive"]
                         and rec["detector_silent_on_double"]
                         and rec["one_hop_agrees_primitive_dead_mod2"]
                         and rec["primitive_in_real_lattice"])
        fired += int(rec["detector_fires_on_primitive"])
        ok = ok and rec["passed"]
        out.append(rec)
        print(json.dumps(rec))
    summ = {"chains": len(out), "detector_fired": fired,
            "all_controls_passed": ok and bool(out),
            "note": "the real lattice contains pi(D) on every chain, so no "
                    "real chain can be certified dead; the detector is shown "
                    "able to fire on a synthetic doubled system, and the "
                    "independent one-hop solver agrees"}
    print(json.dumps({"summary": summ}))
    _dump(args, "probe", summ, out)
    return 0 if summ["all_controls_passed"] else 2


def mode_period(args, rows):
    """The window axes on the completed graph."""
    sel = [r for r in rows if not Completed(
        GS.Folded(GS.gamma_gens(r["chain"], r["g_gen"]))).finite]
    if args.chains:
        a, b = args.chains.split(":")
        sel = sel[int(a or 0):int(b or len(sel))]
    L = int(args.radii.split(",")[0])
    out, ok = [], True
    for r in sel:
        ch = tuple(r["chain"])
        g = r["g_gen"]
        cp = Completed(GS.Folded(GS.gamma_gens(ch, g)))
        sl = PS.chain_slots_g(ch, g, args.k, args.k)
        z2, z3 = sl["h2"]["zeta"], sl["h3"]["zeta"]
        # does zeta act trivially on the completed graph?
        ball = [v for v in reduced_words(args.radius)]
        triv2 = all(cp.walk(cp.trace(v), z2) == cp.trace(v) for v in ball)
        triv3 = all(cp.walk(cp.trace(v), z3) == cp.trace(v) for v in ball)
        seen = []
        for k0 in range(-args.k, args.k + 1):
            for k1 in range(-args.k, args.k + 1):
                for k2 in range(-args.k, args.k + 1):
                    for k3 in range(-args.k, args.k + 1):
                        ops, dfc, h = GS.window_data(ch, g, sl,
                                                     (k0, k1, k2, k3))
                        states = sigma_states(cp, ch, h)
                        rws = build_rows(cp, states, L, args.align)
                        Z = ZEchelon(order=DEEP_FIRST)
                        for tag, row in rws.items():
                            Z.add(row, tag)
                        piD = defect_image(cp, dfc)
                        full, _ = coverage(cp, Z, rws)
                        seen.append({"w": [k0, k1, k2, k3],
                                     "in": Z.member(piD)[0],
                                     "aug": sum(piD.values()),
                                     "margin": L - full})
        rec = {"chain": r["chain"], "g": g, "K": args.k, "L": L,
               "zeta2_acts_trivially_on_ball": triv2,
               "zeta3_acts_trivially_on_ball": triv3,
               "windows": len(seen),
               "windows_with_piD_in_lattice": sum(1 for s in seen if s["in"]),
               "margins": sorted({s["margin"] for s in seen}),
               "augmentations": sorted({s["aug"] for s in seen})}
        rec["all_windows_solvable"] = (
            rec["windows_with_piD_in_lattice"] == rec["windows"])
        ok = ok and rec["augmentations"] == [0]
        out.append(rec)
        print(json.dumps(rec))
    summ = {"chains": len(out),
            "all_windows_solvable": sum(1 for o in out
                                        if o["all_windows_solvable"]),
            "zeta_trivial_on_ball": sum(
                1 for o in out if o["zeta2_acts_trivially_on_ball"]
                and o["zeta3_acts_trivially_on_ball"]),
            "controls_passed": ok and bool(out)}
    print(json.dumps({"summary": summ}))
    _dump(args, "period", summ, out)
    return 0 if summ["controls_passed"] else 2


def _dump(args, name, summ, rows):
    if args.json:
        Path(args.json).write_text(json.dumps(
            {"schema": f"acsolverx.w2h.{name}.v1",
             "summary": summ, "rows": rows}, indent=1))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=("identity", "finite", "image",
                                       "lift", "probe", "period"),
                    default="identity")
    ap.add_argument("--radius", type=int, default=6,
                    help="ball of v used by the control modes")
    ap.add_argument("--radii", type=str, default="8,10,12",
                    help="comma-separated |v| ceilings for --mode image")
    ap.add_argument("--align", type=int, default=0,
                    help="radius of the aligned word family "
                         "(0 = plain ball only)")
    ap.add_argument("--resid-rho", type=int, default=0,
                    help="hop depth for the telescoping residual "
                         "(0 = same as --rho)")
    ap.add_argument("--rho", type=int, default=6,
                    help="module ball for --mode lift")
    ap.add_argument("--k", type=int, default=1)
    ap.add_argument("--chains", type=str, default="")
    ap.add_argument("--stratum-only", action="store_true")
    ap.add_argument("--json", type=str, default="")
    args = ap.parse_args()

    c1 = LV.analyze(PS.WITNESS, fixed_h=PS.CODEX_H)
    got = (c1["defect_terms"], c1["defect_l1"], c1["defect_augmentation"])
    print(json.dumps({"control": "fixed_h_witness", "defect": list(got),
                      "want": [21, 48, 0], "passed": got == (21, 48, 0)}))
    if got != (21, 48, 0):
        return 2

    rows = GS.load_rows()
    return {"identity": mode_identity, "finite": mode_finite,
            "image": mode_image, "lift": mode_lift,
            "probe": mode_probe, "period": mode_period}[args.mode](args, rows)


if __name__ == "__main__":
    sys.exit(main())
